# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 9.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by core Perl only.  The format and even the
# name or existence of this file are subject to change without notice.  Don't
# use it directly.  Use Unicode::UCD to access the Unicode character data
# base.


return <<'END';
V56
9757
9758
9977
9978
9994
9998
127877
127878
127939
127941
127946
127948
128066
128068
128070
128081
128110
128111
128112
128121
128124
128125
128129
128132
128133
128136
128170
128171
128373
128374
128378
128379
128400
128401
128405
128407
128581
128584
128587
128592
128675
128676
128692
128695
128704
128705
129304
129311
129318
129319
129328
129329
129331
129338
129340
129343
END
