//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.34011
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonobo.Git.Server.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bonobo.Git.Server.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account with this username already exists..
        /// </summary>
        public static string Account_Create_AccountAlreadyExists {
            get {
                return ResourceManager.GetString("Account_Create_AccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account information.
        /// </summary>
        public static string Account_Create_AccountInformation {
            get {
                return ResourceManager.GetString("Account_Create_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm Password.
        /// </summary>
        public static string Account_Create_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account_Create_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Account_Create_Email {
            get {
                return ResourceManager.GetString("Account_Create_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Account_Create_Name {
            get {
                return ResourceManager.GetString("Account_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string Account_Create_Password {
            get {
                return ResourceManager.GetString("Account_Create_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create new account.
        /// </summary>
        public static string Account_Create_Submit {
            get {
                return ResourceManager.GetString("Account_Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The user was created successfully..
        /// </summary>
        public static string Account_Create_Success {
            get {
                return ResourceManager.GetString("Account_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Surname.
        /// </summary>
        public static string Account_Create_Surname {
            get {
                return ResourceManager.GetString("Account_Create_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create New Account.
        /// </summary>
        public static string Account_Create_Title {
            get {
                return ResourceManager.GetString("Account_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Account_Create_Unsuccessfull {
            get {
                return ResourceManager.GetString("Account_Create_Unsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username.
        /// </summary>
        public static string Account_Create_Username {
            get {
                return ResourceManager.GetString("Account_Create_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can&apos;t delete yourself..
        /// </summary>
        public static string Account_Delete_DeleteCurrentUser {
            get {
                return ResourceManager.GetString("Account_Delete_DeleteCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The user was deleted..
        /// </summary>
        public static string Account_Delete_Success {
            get {
                return ResourceManager.GetString("Account_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back to the list.
        /// </summary>
        public static string Account_Detail_Back {
            get {
                return ResourceManager.GetString("Account_Detail_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Account_Detail_Delete {
            get {
                return ResourceManager.GetString("Account_Detail_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string Account_Detail_Edit {
            get {
                return ResourceManager.GetString("Account_Detail_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Account_Detail_Email {
            get {
                return ResourceManager.GetString("Account_Detail_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Account_Detail_Name {
            get {
                return ResourceManager.GetString("Account_Detail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Roles.
        /// </summary>
        public static string Account_Detail_Roles {
            get {
                return ResourceManager.GetString("Account_Detail_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Surname.
        /// </summary>
        public static string Account_Detail_Surname {
            get {
                return ResourceManager.GetString("Account_Detail_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Detail.
        /// </summary>
        public static string Account_Detail_Title {
            get {
                return ResourceManager.GetString("Account_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username.
        /// </summary>
        public static string Account_Detail_Username {
            get {
                return ResourceManager.GetString("Account_Detail_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back to list.
        /// </summary>
        public static string Account_Edit_Back {
            get {
                return ResourceManager.GetString("Account_Edit_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Account_Edit_Cancel {
            get {
                return ResourceManager.GetString("Account_Edit_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t remove yourself from administrators..
        /// </summary>
        public static string Account_Edit_CannotRemoveYourselfFromAdminRole {
            get {
                return ResourceManager.GetString("Account_Edit_CannotRemoveYourselfFromAdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm Password.
        /// </summary>
        public static string Account_Edit_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account_Edit_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current Password.
        /// </summary>
        public static string Account_Edit_CurrentPassword {
            get {
                return ResourceManager.GetString("Account_Edit_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Account_Edit_Email {
            get {
                return ResourceManager.GetString("Account_Edit_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Account_Edit_Name {
            get {
                return ResourceManager.GetString("Account_Edit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Password.
        /// </summary>
        public static string Account_Edit_NewPassword {
            get {
                return ResourceManager.GetString("Account_Edit_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Current password should not be empty..
        /// </summary>
        public static string Account_Edit_OldPasswordEmpty {
            get {
                return ResourceManager.GetString("Account_Edit_OldPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password does not match the current password..
        /// </summary>
        public static string Account_Edit_OldPasswordIncorrect {
            get {
                return ResourceManager.GetString("Account_Edit_OldPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Roles.
        /// </summary>
        public static string Account_Edit_Roles {
            get {
                return ResourceManager.GetString("Account_Edit_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrators have access to all repositories and are allowed to do all operations with repositories, teams and users..
        /// </summary>
        public static string Account_Edit_RolesHint {
            get {
                return ResourceManager.GetString("Account_Edit_RolesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string Account_Edit_Submit {
            get {
                return ResourceManager.GetString("Account_Edit_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Surname.
        /// </summary>
        public static string Account_Edit_Surname {
            get {
                return ResourceManager.GetString("Account_Edit_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit User Account.
        /// </summary>
        public static string Account_Edit_Title {
            get {
                return ResourceManager.GetString("Account_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account edit was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Account_Edit_Unsuccessfull {
            get {
                return ResourceManager.GetString("Account_Edit_Unsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The account was updated successfully..
        /// </summary>
        public static string Account_Edit_UpdateSuccess {
            get {
                return ResourceManager.GetString("Account_Edit_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create new user.
        /// </summary>
        public static string Account_Index_Create {
            get {
                return ResourceManager.GetString("Account_Index_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à User Management.
        /// </summary>
        public static string Account_Index_Title {
            get {
                return ResourceManager.GetString("Account_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Users.
        /// </summary>
        public static string Account_Index_Users {
            get {
                return ResourceManager.GetString("Account_Index_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à MM/dd/yyyy hh:mm.
        /// </summary>
        public static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back.
        /// </summary>
        public static string Delete_Back {
            get {
                return ResourceManager.GetString("Delete_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Delete_Confirm {
            get {
                return ResourceManager.GetString("Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Do you really want to delete {0}?.
        /// </summary>
        public static string Delete_ConfirmationText {
            get {
                return ResourceManager.GetString("Delete_ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete Confirmation.
        /// </summary>
        public static string Delete_Title {
            get {
                return ResourceManager.GetString("Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Grid_Delete {
            get {
                return ResourceManager.GetString("Grid_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string Grid_Edit {
            get {
                return ResourceManager.GetString("Grid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Thank you!.
        /// </summary>
        public static string Home_About_Thanks {
            get {
                return ResourceManager.GetString("Home_About_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonobo Git Server is using a few open source and freeware projects. Many thanks to all authors and contributors for their great work..
        /// </summary>
        public static string Home_About_Thanks_p {
            get {
                return ResourceManager.GetString("Home_About_Thanks_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string Home_About_Title {
            get {
                return ResourceManager.GetString("Home_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred when processing your request. Please try again or contact the system administrator..
        /// </summary>
        public static string Home_Error_Text {
            get {
                return ResourceManager.GetString("Home_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An Error Occurred.
        /// </summary>
        public static string Home_Error_Title {
            get {
                return ResourceManager.GetString("Home_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account Information.
        /// </summary>
        public static string Home_LogOn_AccountInformation {
            get {
                return ResourceManager.GetString("Home_LogOn_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Home_LogOn_Failed {
            get {
                return ResourceManager.GetString("Home_LogOn_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log On.
        /// </summary>
        public static string Home_LogOn_LogOn {
            get {
                return ResourceManager.GetString("Home_LogOn_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string Home_LogOn_Password {
            get {
                return ResourceManager.GetString("Home_LogOn_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remember me?.
        /// </summary>
        public static string Home_LogOn_RememberMe {
            get {
                return ResourceManager.GetString("Home_LogOn_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log On.
        /// </summary>
        public static string Home_LogOn_Title {
            get {
                return ResourceManager.GetString("Home_LogOn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username.
        /// </summary>
        public static string Home_LogOn_Username {
            get {
                return ResourceManager.GetString("Home_LogOn_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The username or password provided is incorrect..
        /// </summary>
        public static string Home_LogOn_UsernamePasswordIncorrect {
            get {
                return ResourceManager.GetString("Home_LogOn_UsernamePasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The page you were looking for wasn&apos;t found. Please try again or contact the system administrator..
        /// </summary>
        public static string Home_PageNotFound_Text {
            get {
                return ResourceManager.GetString("Home_PageNotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 404 Page Not Found.
        /// </summary>
        public static string Home_PageNotFound_Title {
            get {
                return ResourceManager.GetString("Home_PageNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A server error occurred when processing your request. Please try again or contact the system administrator..
        /// </summary>
        public static string Home_ServerError_Text {
            get {
                return ResourceManager.GetString("Home_ServerError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 500 Server Error.
        /// </summary>
        public static string Home_ServerError_Title {
            get {
                return ResourceManager.GetString("Home_ServerError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You don&apos;t have permission for the selected action or page..
        /// </summary>
        public static string Home_Unauthorized_Text {
            get {
                return ResourceManager.GetString("Home_Unauthorized_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unauthorized.
        /// </summary>
        public static string Home_Unauthorized_Title {
            get {
                return ResourceManager.GetString("Home_Unauthorized_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Item wasn&apos;t found.
        /// </summary>
        public static string Item_NotFound {
            get {
                return ResourceManager.GetString("Item_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string Layout_About {
            get {
                return ResourceManager.GetString("Layout_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account Settings.
        /// </summary>
        public static string Layout_AccountSettings {
            get {
                return ResourceManager.GetString("Layout_AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administration.
        /// </summary>
        public static string Layout_Administration {
            get {
                return ResourceManager.GetString("Layout_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Global Settings.
        /// </summary>
        public static string Layout_AdministrationGlobalSettings {
            get {
                return ResourceManager.GetString("Layout_AdministrationGlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repositories.
        /// </summary>
        public static string Layout_AdministrationRepositories {
            get {
                return ResourceManager.GetString("Layout_AdministrationRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Teams.
        /// </summary>
        public static string Layout_AdministrationTeams {
            get {
                return ResourceManager.GetString("Layout_AdministrationTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Users.
        /// </summary>
        public static string Layout_AdministrationUsers {
            get {
                return ResourceManager.GetString("Layout_AdministrationUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All rights reserved..
        /// </summary>
        public static string Layout_Footer_Copyright {
            get {
                return ResourceManager.GetString("Layout_Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string Layout_Home {
            get {
                return ResourceManager.GetString("Layout_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log Off.
        /// </summary>
        public static string Layout_LogOff {
            get {
                return ResourceManager.GetString("Layout_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log On.
        /// </summary>
        public static string Layout_LogOn {
            get {
                return ResourceManager.GetString("Layout_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create new account.
        /// </summary>
        public static string Layout_Register {
            get {
                return ResourceManager.GetString("Layout_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repositories.
        /// </summary>
        public static string Layout_Repositories {
            get {
                return ResourceManager.GetString("Layout_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonobo Git Server.
        /// </summary>
        public static string Layout_Title {
            get {
                return ResourceManager.GetString("Layout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string Repository_AddressBar_Root {
            get {
                return ResourceManager.GetString("Repository_AddressBar_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrators have full access to the repository. They can modify repository metadata or delete the repository..
        /// </summary>
        public static string Repository_AdministratorsHint {
            get {
                return ResourceManager.GetString("Repository_AdministratorsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If anonymous access is allowed, everyone can pull or clone the repository and view repository metadata. Push is available only if set in Global Settings..
        /// </summary>
        public static string Repository_AllowAnonymousHint {
            get {
                return ResourceManager.GetString("Repository_AllowAnonymousHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Added.
        /// </summary>
        public static string Repository_Commit_Added {
            get {
                return ResourceManager.GetString("Repository_Commit_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author.
        /// </summary>
        public static string Repository_Commit_Author {
            get {
                return ResourceManager.GetString("Repository_Commit_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Repository_Commit_AuthorEmail {
            get {
                return ResourceManager.GetString("Repository_Commit_AuthorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changed files.
        /// </summary>
        public static string Repository_Commit_Changes {
            get {
                return ResourceManager.GetString("Repository_Commit_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copied.
        /// </summary>
        public static string Repository_Commit_Copied {
            get {
                return ResourceManager.GetString("Repository_Commit_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        public static string Repository_Commit_Date {
            get {
                return ResourceManager.GetString("Repository_Commit_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleted.
        /// </summary>
        public static string Repository_Commit_Deleted {
            get {
                return ResourceManager.GetString("Repository_Commit_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commit Detail.
        /// </summary>
        public static string Repository_Commit_Detail {
            get {
                return ResourceManager.GetString("Repository_Commit_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commit.
        /// </summary>
        public static string Repository_Commit_ID {
            get {
                return ResourceManager.GetString("Repository_Commit_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message.
        /// </summary>
        public static string Repository_Commit_Message {
            get {
                return ResourceManager.GetString("Repository_Commit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modified.
        /// </summary>
        public static string Repository_Commit_Modified {
            get {
                return ResourceManager.GetString("Repository_Commit_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parents.
        /// </summary>
        public static string Repository_Commit_Parents {
            get {
                return ResourceManager.GetString("Repository_Commit_Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Renamed.
        /// </summary>
        public static string Repository_Commit_Renamed {
            get {
                return ResourceManager.GetString("Repository_Commit_Renamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tree.
        /// </summary>
        public static string Repository_Commit_TreeID {
            get {
                return ResourceManager.GetString("Repository_Commit_TreeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Type Changed.
        /// </summary>
        public static string Repository_Commit_TypeChanged {
            get {
                return ResourceManager.GetString("Repository_Commit_TypeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commits.
        /// </summary>
        public static string Repository_Commits_Title {
            get {
                return ResourceManager.GetString("Repository_Commits_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back to the list.
        /// </summary>
        public static string Repository_Create_Back {
            get {
                return ResourceManager.GetString("Repository_Create_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A directory with this name already exists in your repository folder. Delete this directory or choose another name and try again..
        /// </summary>
        public static string Repository_Create_DirectoryExists {
            get {
                return ResourceManager.GetString("Repository_Create_DirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repository creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Repository_Create_Fail {
            get {
                return ResourceManager.GetString("Repository_Create_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repository with selected name already exists..
        /// </summary>
        public static string Repository_Create_Failure {
            get {
                return ResourceManager.GetString("Repository_Create_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repository information.
        /// </summary>
        public static string Repository_Create_Informations {
            get {
                return ResourceManager.GetString("Repository_Create_Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name shouldn&apos;t contain only whitespace..
        /// </summary>
        public static string Repository_Create_NameFailure {
            get {
                return ResourceManager.GetString("Repository_Create_NameFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create.
        /// </summary>
        public static string Repository_Create_Submit {
            get {
                return ResourceManager.GetString("Repository_Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repository was created successfully..
        /// </summary>
        public static string Repository_Create_Success {
            get {
                return ResourceManager.GetString("Repository_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create New Repository.
        /// </summary>
        public static string Repository_Create_Title {
            get {
                return ResourceManager.GetString("Repository_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repository was deleted successfully..
        /// </summary>
        public static string Repository_Delete_Success {
            get {
                return ResourceManager.GetString("Repository_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administrators.
        /// </summary>
        public static string Repository_Detail_Administrators {
            get {
                return ResourceManager.GetString("Repository_Detail_Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Anonymous.
        /// </summary>
        public static string Repository_Detail_Anonymous {
            get {
                return ResourceManager.GetString("Repository_Detail_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back to the list.
        /// </summary>
        public static string Repository_Detail_Back {
            get {
                return ResourceManager.GetString("Repository_Detail_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Repository_Detail_Delete {
            get {
                return ResourceManager.GetString("Repository_Detail_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Repository_Detail_Description {
            get {
                return ResourceManager.GetString("Repository_Detail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details.
        /// </summary>
        public static string Repository_Detail_Detail {
            get {
                return ResourceManager.GetString("Repository_Detail_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string Repository_Detail_Edit {
            get {
                return ResourceManager.GetString("Repository_Detail_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Admin.
        /// </summary>
        public static string Repository_Detail_IsCurrentUserAdmin {
            get {
                return ResourceManager.GetString("Repository_Detail_IsCurrentUserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Git Repository Location.
        /// </summary>
        public static string Repository_Detail_Location {
            get {
                return ResourceManager.GetString("Repository_Detail_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Repository_Detail_Name {
            get {
                return ResourceManager.GetString("Repository_Detail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string Repository_Detail_No {
            get {
                return ResourceManager.GetString("Repository_Detail_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string Repository_Detail_Status {
            get {
                return ResourceManager.GetString("Repository_Detail_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Teams.
        /// </summary>
        public static string Repository_Detail_Teams {
            get {
                return ResourceManager.GetString("Repository_Detail_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repository Detail.
        /// </summary>
        public static string Repository_Detail_Title {
            get {
                return ResourceManager.GetString("Repository_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contributors.
        /// </summary>
        public static string Repository_Detail_Users {
            get {
                return ResourceManager.GetString("Repository_Detail_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string Repository_Detail_Yes {
            get {
                return ResourceManager.GetString("Repository_Detail_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back to the list.
        /// </summary>
        public static string Repository_Edit_Back {
            get {
                return ResourceManager.GetString("Repository_Edit_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can&apos;t remove yourself from administrators..
        /// </summary>
        public static string Repository_Edit_CantRemoveYourself {
            get {
                return ResourceManager.GetString("Repository_Edit_CantRemoveYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repository update was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Repository_Edit_Fail {
            get {
                return ResourceManager.GetString("Repository_Edit_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string Repository_Edit_Submit {
            get {
                return ResourceManager.GetString("Repository_Edit_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit Repository.
        /// </summary>
        public static string Repository_Edit_Title {
            get {
                return ResourceManager.GetString("Repository_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repository was updated successfully..
        /// </summary>
        public static string Repository_Edit_UpdateSuccess {
            get {
                return ResourceManager.GetString("Repository_Edit_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Administered Repositories.
        /// </summary>
        public static string Repository_Index_AdministratedRepositories {
            get {
                return ResourceManager.GetString("Repository_Index_AdministratedRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All Repositories.
        /// </summary>
        public static string Repository_Index_AllRepositories {
            get {
                return ResourceManager.GetString("Repository_Index_AllRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create new repository.
        /// </summary>
        public static string Repository_Index_CreateNew {
            get {
                return ResourceManager.GetString("Repository_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string Repository_Index_No {
            get {
                return ResourceManager.GetString("Repository_Index_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repositories.
        /// </summary>
        public static string Repository_Index_Repositories {
            get {
                return ResourceManager.GetString("Repository_Index_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repository Management.
        /// </summary>
        public static string Repository_Index_Title {
            get {
                return ResourceManager.GetString("Repository_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string Repository_Index_Yes {
            get {
                return ResourceManager.GetString("Repository_Index_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repository Browser.
        /// </summary>
        public static string Repository_Layout_Browse {
            get {
                return ResourceManager.GetString("Repository_Layout_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Commits.
        /// </summary>
        public static string Repository_Layout_Commits {
            get {
                return ResourceManager.GetString("Repository_Layout_Commits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Switch current branch.
        /// </summary>
        public static string Repository_SwitchBranch {
            get {
                return ResourceManager.GetString("Repository_SwitchBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Teams have access to the repository. They can clone, push or pull and view repository metadata. All users in the team can access this repository..
        /// </summary>
        public static string Repository_TeamsHint {
            get {
                return ResourceManager.GetString("Repository_TeamsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author.
        /// </summary>
        public static string Repository_Tree_Author {
            get {
                return ResourceManager.GetString("Repository_Tree_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date.
        /// </summary>
        public static string Repository_Tree_CommitDate {
            get {
                return ResourceManager.GetString("Repository_Tree_CommitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message.
        /// </summary>
        public static string Repository_Tree_CommitMessage {
            get {
                return ResourceManager.GetString("Repository_Tree_CommitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download.
        /// </summary>
        public static string Repository_Tree_Download {
            get {
                return ResourceManager.GetString("Repository_Tree_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Repository_Tree_Name {
            get {
                return ResourceManager.GetString("Repository_Tree_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Preview of this file is not supported..
        /// </summary>
        public static string Repository_Tree_PreviewNotSupported {
            get {
                return ResourceManager.GetString("Repository_Tree_PreviewNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Raw.
        /// </summary>
        public static string Repository_Tree_RawDisplay {
            get {
                return ResourceManager.GetString("Repository_Tree_RawDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Browse Repository.
        /// </summary>
        public static string Repository_Tree_Title {
            get {
                return ResourceManager.GetString("Repository_Tree_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Download ZIP.
        /// </summary>
        public static string Repository_Tree_Zip {
            get {
                return ResourceManager.GetString("Repository_Tree_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Users have access to the repository. They can clone, push or pull and view repository metadata..
        /// </summary>
        public static string Repository_UsersHint {
            get {
                return ResourceManager.GetString("Repository_UsersHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow push for anonymous repositories.
        /// </summary>
        public static string Settings_Global_AllowAnonymousPush {
            get {
                return ResourceManager.GetString("Settings_Global_AllowAnonymousPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow anonymous registration.
        /// </summary>
        public static string Settings_Global_AllowAnonymousRegistration {
            get {
                return ResourceManager.GetString("Settings_Global_AllowAnonymousRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If checkbox is unchecked, only administrators can add new users and anonymous user registration is disabled..
        /// </summary>
        public static string Settings_Global_AllowAnonymousRegistration_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_AllowAnonymousRegistration_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Allow user repository creation.
        /// </summary>
        public static string Settings_Global_AllowUserRepositoryCreation {
            get {
                return ResourceManager.GetString("Settings_Global_AllowUserRepositoryCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à If checkbox is unchecked, only administrators can create repositories..
        /// </summary>
        public static string Settings_Global_AllowUserRepositoryCreation_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_AllowUserRepositoryCreation_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string Settings_Global_DefaultLanguage {
            get {
                return ResourceManager.GetString("Settings_Global_DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language set by default in the application..
        /// </summary>
        public static string Settings_Global_DefaultLanguage_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_DefaultLanguage_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à All repositories are stored in this directory..
        /// </summary>
        public static string Settings_Global_DirectoryHint {
            get {
                return ResourceManager.GetString("Settings_Global_DirectoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repository Directory.
        /// </summary>
        public static string Settings_Global_RepositoryPath {
            get {
                return ResourceManager.GetString("Settings_Global_RepositoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Settings update was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Settings_Index_Failed {
            get {
                return ResourceManager.GetString("Settings_Index_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string Settings_Index_Save {
            get {
                return ResourceManager.GetString("Settings_Index_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Global Settings.
        /// </summary>
        public static string Settings_Index_Title {
            get {
                return ResourceManager.GetString("Settings_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Global settings updated successfully..
        /// </summary>
        public static string Settings_Index_UpdateSuccess {
            get {
                return ResourceManager.GetString("Settings_Index_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Selected path does not exist. Please create the folder or choose a different path..
        /// </summary>
        public static string Settings_RepositoryPathNotExists {
            get {
                return ResourceManager.GetString("Settings_RepositoryPathNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You don&apos;t have privileges to write to the selected folder. Please choose a different path..
        /// </summary>
        public static string Settings_RepositoryPathUnauthorized {
            get {
                return ResourceManager.GetString("Settings_RepositoryPathUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back to the list.
        /// </summary>
        public static string Team_Create_Back {
            get {
                return ResourceManager.GetString("Team_Create_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New team creation was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Team_Create_Fail {
            get {
                return ResourceManager.GetString("Team_Create_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Team with selected name already exists. Team wasn&apos;t created..
        /// </summary>
        public static string Team_Create_Failure {
            get {
                return ResourceManager.GetString("Team_Create_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save.
        /// </summary>
        public static string Team_Create_Submit {
            get {
                return ResourceManager.GetString("Team_Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The team was created successfully..
        /// </summary>
        public static string Team_Create_Success {
            get {
                return ResourceManager.GetString("Team_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Team information.
        /// </summary>
        public static string Team_Create_TeamInformations {
            get {
                return ResourceManager.GetString("Team_Create_TeamInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create New Team.
        /// </summary>
        public static string Team_Create_Title {
            get {
                return ResourceManager.GetString("Team_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The team was deleted..
        /// </summary>
        public static string Team_Delete_Success {
            get {
                return ResourceManager.GetString("Team_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back to the list.
        /// </summary>
        public static string Team_Detail_Back {
            get {
                return ResourceManager.GetString("Team_Detail_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Team_Detail_Delete {
            get {
                return ResourceManager.GetString("Team_Detail_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Team_Detail_Description {
            get {
                return ResourceManager.GetString("Team_Detail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string Team_Detail_Edit {
            get {
                return ResourceManager.GetString("Team_Detail_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Members.
        /// </summary>
        public static string Team_Detail_Members {
            get {
                return ResourceManager.GetString("Team_Detail_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name.
        /// </summary>
        public static string Team_Detail_Name {
            get {
                return ResourceManager.GetString("Team_Detail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Repositories.
        /// </summary>
        public static string Team_Detail_Repositories {
            get {
                return ResourceManager.GetString("Team_Detail_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Team Detail.
        /// </summary>
        public static string Team_Detail_Title {
            get {
                return ResourceManager.GetString("Team_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back to the list.
        /// </summary>
        public static string Team_Edit_Back {
            get {
                return ResourceManager.GetString("Team_Edit_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Team update was unsuccessful. Please correct the errors and try again..
        /// </summary>
        public static string Team_Edit_Failure {
            get {
                return ResourceManager.GetString("Team_Edit_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update.
        /// </summary>
        public static string Team_Edit_Submit {
            get {
                return ResourceManager.GetString("Team_Edit_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit Team.
        /// </summary>
        public static string Team_Edit_Title {
            get {
                return ResourceManager.GetString("Team_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Team was updated successfully..
        /// </summary>
        public static string Team_Edit_UpdateSuccess {
            get {
                return ResourceManager.GetString("Team_Edit_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create new team.
        /// </summary>
        public static string Team_Index_CreateNew {
            get {
                return ResourceManager.GetString("Team_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Teams.
        /// </summary>
        public static string Team_Index_Teams {
            get {
                return ResourceManager.GetString("Team_Index_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Team Management.
        /// </summary>
        public static string Team_Index_Title {
            get {
                return ResourceManager.GetString("Team_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;{0}&quot; and &quot;{1}&quot; must have the same value..
        /// </summary>
        public static string Validation_Compare {
            get {
                return ResourceManager.GetString("Validation_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;{0}&quot; is not a valid email address..
        /// </summary>
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;{0}&quot; contains characters that can&apos;t be in a file or directory name..
        /// </summary>
        public static string Validation_FileName {
            get {
                return ResourceManager.GetString("Validation_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;{0}&quot; is mandatory..
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &quot;{0}&quot; should be shorter than {1} characters..
        /// </summary>
        public static string Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation_StringLength", resourceCulture);
            }
        }
    }
}
