//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class cs_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal cs_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources.cs_RU", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учетная запись с таким логином уже существует..
        /// </summary>
        internal static string Account_Create_AccountAlreadyExists {
            get {
                return ResourceManager.GetString("Account_Create_AccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация об учетной записи.
        /// </summary>
        internal static string Account_Create_AccountInformation {
            get {
                return ResourceManager.GetString("Account_Create_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите пароль.
        /// </summary>
        internal static string Account_Create_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account_Create_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта.
        /// </summary>
        internal static string Account_Create_Email {
            get {
                return ResourceManager.GetString("Account_Create_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string Account_Create_Name {
            get {
                return ResourceManager.GetString("Account_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Account_Create_Password {
            get {
                return ResourceManager.GetString("Account_Create_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать учетную запись.
        /// </summary>
        internal static string Account_Create_Submit {
            get {
                return ResourceManager.GetString("Account_Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь был успешно создан..
        /// </summary>
        internal static string Account_Create_Success {
            get {
                return ResourceManager.GetString("Account_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обращение.
        /// </summary>
        internal static string Account_Create_Surname {
            get {
                return ResourceManager.GetString("Account_Create_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать учетную запись.
        /// </summary>
        internal static string Account_Create_Title {
            get {
                return ResourceManager.GetString("Account_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создание учетной записи не удалось. Исправьте ошибки и попробуйте еще раз..
        /// </summary>
        internal static string Account_Create_Unsuccessfull {
            get {
                return ResourceManager.GetString("Account_Create_Unsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        internal static string Account_Create_Username {
            get {
                return ResourceManager.GetString("Account_Create_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете удалить свою учетную запись.
        /// </summary>
        internal static string Account_Delete_DeleteCurrentUser {
            get {
                return ResourceManager.GetString("Account_Delete_DeleteCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь был удален..
        /// </summary>
        internal static string Account_Delete_Success {
            get {
                return ResourceManager.GetString("Account_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратно к списку.
        /// </summary>
        internal static string Account_Detail_Back {
            get {
                return ResourceManager.GetString("Account_Detail_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Account_Detail_Delete {
            get {
                return ResourceManager.GetString("Account_Detail_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        internal static string Account_Detail_Edit {
            get {
                return ResourceManager.GetString("Account_Detail_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта.
        /// </summary>
        internal static string Account_Detail_Email {
            get {
                return ResourceManager.GetString("Account_Detail_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string Account_Detail_Name {
            get {
                return ResourceManager.GetString("Account_Detail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        internal static string Account_Detail_Roles {
            get {
                return ResourceManager.GetString("Account_Detail_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обращение.
        /// </summary>
        internal static string Account_Detail_Surname {
            get {
                return ResourceManager.GetString("Account_Detail_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о пользователе.
        /// </summary>
        internal static string Account_Detail_Title {
            get {
                return ResourceManager.GetString("Account_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        internal static string Account_Detail_Username {
            get {
                return ResourceManager.GetString("Account_Detail_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Свойства учетной записи.
        /// </summary>
        internal static string Account_Edit_AccountInformation {
            get {
                return ResourceManager.GetString("Account_Edit_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратно к списку.
        /// </summary>
        internal static string Account_Edit_Back {
            get {
                return ResourceManager.GetString("Account_Edit_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string Account_Edit_Cancel {
            get {
                return ResourceManager.GetString("Account_Edit_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете удалить сами себя из Администраторов.
        /// </summary>
        internal static string Account_Edit_CannotRemoveYourselfFromAdminRole {
            get {
                return ResourceManager.GetString("Account_Edit_CannotRemoveYourselfFromAdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите пароль.
        /// </summary>
        internal static string Account_Edit_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account_Edit_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий пароль.
        /// </summary>
        internal static string Account_Edit_CurrentPassword {
            get {
                return ResourceManager.GetString("Account_Edit_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта.
        /// </summary>
        internal static string Account_Edit_Email {
            get {
                return ResourceManager.GetString("Account_Edit_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string Account_Edit_Name {
            get {
                return ResourceManager.GetString("Account_Edit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        internal static string Account_Edit_NewPassword {
            get {
                return ResourceManager.GetString("Account_Edit_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текущий пароль не может быть пустым.
        /// </summary>
        internal static string Account_Edit_OldPasswordEmpty {
            get {
                return ResourceManager.GetString("Account_Edit_OldPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль не совпадает с текущим.
        /// </summary>
        internal static string Account_Edit_OldPasswordIncorrect {
            get {
                return ResourceManager.GetString("Account_Edit_OldPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        internal static string Account_Edit_Roles {
            get {
                return ResourceManager.GetString("Account_Edit_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администраторы имеют доступ ко всем репозиториям и им разрешены все операции с репозиториями , командами и пользователями..
        /// </summary>
        internal static string Account_Edit_RolesHint {
            get {
                return ResourceManager.GetString("Account_Edit_RolesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Account_Edit_Submit {
            get {
                return ResourceManager.GetString("Account_Edit_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обращение.
        /// </summary>
        internal static string Account_Edit_Surname {
            get {
                return ResourceManager.GetString("Account_Edit_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить свойства учетной записи.
        /// </summary>
        internal static string Account_Edit_Title {
            get {
                return ResourceManager.GetString("Account_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование учетной записи не удалось. Исправьте ошибки и попробуйте еще раз..
        /// </summary>
        internal static string Account_Edit_Unsuccessfull {
            get {
                return ResourceManager.GetString("Account_Edit_Unsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учетная запись была обновлена..
        /// </summary>
        internal static string Account_Edit_UpdateSuccess {
            get {
                return ResourceManager.GetString("Account_Edit_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать нового пользователя.
        /// </summary>
        internal static string Account_Index_Create {
            get {
                return ResourceManager.GetString("Account_Index_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление пользователями.
        /// </summary>
        internal static string Account_Index_Title {
            get {
                return ResourceManager.GetString("Account_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        internal static string Account_Index_Users {
            get {
                return ResourceManager.GetString("Account_Index_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd.MM.yyyy hh:mm.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        internal static string Delete_Back {
            get {
                return ResourceManager.GetString("Delete_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Delete_Confirm {
            get {
                return ResourceManager.GetString("Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы действительно хотите удалить {0}?.
        /// </summary>
        internal static string Delete_ConfirmationText {
            get {
                return ResourceManager.GetString("Delete_ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердите удаление.
        /// </summary>
        internal static string Delete_Title {
            get {
                return ResourceManager.GetString("Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно прав для запрашиваемого проекта.
        /// </summary>
        internal static string GitAccess_ProjectForbidden {
            get {
                return ResourceManager.GetString("GitAccess_ProjectForbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Grid_Delete {
            get {
                return ResourceManager.GetString("Grid_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        internal static string Grid_Edit {
            get {
                return ResourceManager.GetString("Grid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Спасибо.
        /// </summary>
        internal static string Home_About_Thanks {
            get {
                return ResourceManager.GetString("Home_About_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonobo Git Server использует открыте и бесплатные проекты. Огромное спасибо тем кто их разрабатывает и предоставляет.
        /// </summary>
        internal static string Home_About_Thanks_p {
            get {
                return ResourceManager.GetString("Home_About_Thanks_p", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О проекте.
        /// </summary>
        internal static string Home_About_Title {
            get {
                return ResourceManager.GetString("Home_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла непредвиденная ошибка при обработке запроса. Пожалуйста, попробуйте еще раз или обратитесь к администратору системы.
        /// </summary>
        internal static string Home_Error_Text {
            get {
                return ResourceManager.GetString("Home_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка.
        /// </summary>
        internal static string Home_Error_Title {
            get {
                return ResourceManager.GetString("Home_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация об учетной записи.
        /// </summary>
        internal static string Home_LogOn_AccountInformation {
            get {
                return ResourceManager.GetString("Home_LogOn_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход не удался, исправьте ошибки и попробуйте снова.
        /// </summary>
        internal static string Home_LogOn_Failed {
            get {
                return ResourceManager.GetString("Home_LogOn_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string Home_LogOn_LogOn {
            get {
                return ResourceManager.GetString("Home_LogOn_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string Home_LogOn_Password {
            get {
                return ResourceManager.GetString("Home_LogOn_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить?.
        /// </summary>
        internal static string Home_LogOn_RememberMe {
            get {
                return ResourceManager.GetString("Home_LogOn_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string Home_LogOn_Title {
            get {
                return ResourceManager.GetString("Home_LogOn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Логин.
        /// </summary>
        internal static string Home_LogOn_Username {
            get {
                return ResourceManager.GetString("Home_LogOn_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы ввели неправильные логин или пароль..
        /// </summary>
        internal static string Home_LogOn_UsernamePasswordIncorrect {
            get {
                return ResourceManager.GetString("Home_LogOn_UsernamePasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Страница, которую вы запрашиваете не найдена. Пожалуйста, попробуйте еще раз или обратитесь к администратору системы.
        /// </summary>
        internal static string Home_PageNotFound_Text {
            get {
                return ResourceManager.GetString("Home_PageNotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 404 страница не найдена.
        /// </summary>
        internal static string Home_PageNotFound_Title {
            get {
                return ResourceManager.GetString("Home_PageNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to При обработке запроса на сервере произошла ошибка. Пожалуйста, попробуйте еще раз или обратитесь к администратору системы.
        /// </summary>
        internal static string Home_ServerError_Text {
            get {
                return ResourceManager.GetString("Home_ServerError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500 ошибка сервера.
        /// </summary>
        internal static string Home_ServerError_Title {
            get {
                return ResourceManager.GetString("Home_ServerError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У Вас недостаточно прав для совершения этого действия.
        /// </summary>
        internal static string Home_Unauthorized_Text {
            get {
                return ResourceManager.GetString("Home_Unauthorized_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход не выполнен.
        /// </summary>
        internal static string Home_Unauthorized_Title {
            get {
                return ResourceManager.GetString("Home_Unauthorized_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Элемент не найден.
        /// </summary>
        internal static string Item_NotFound {
            get {
                return ResourceManager.GetString("Item_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О системе..
        /// </summary>
        internal static string Layout_About {
            get {
                return ResourceManager.GetString("Layout_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки учетной записи.
        /// </summary>
        internal static string Layout_AccountSettings {
            get {
                return ResourceManager.GetString("Layout_AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрация.
        /// </summary>
        internal static string Layout_Administration {
            get {
                return ResourceManager.GetString("Layout_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Глобальные настройки.
        /// </summary>
        internal static string Layout_AdministrationGlobalSettings {
            get {
                return ResourceManager.GetString("Layout_AdministrationGlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Репозитории.
        /// </summary>
        internal static string Layout_AdministrationRepositories {
            get {
                return ResourceManager.GetString("Layout_AdministrationRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команды.
        /// </summary>
        internal static string Layout_AdministrationTeams {
            get {
                return ResourceManager.GetString("Layout_AdministrationTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        internal static string Layout_AdministrationUsers {
            get {
                return ResourceManager.GetString("Layout_AdministrationUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все права защищены.
        /// </summary>
        internal static string Layout_Footer_Copyright {
            get {
                return ResourceManager.GetString("Layout_Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На главную.
        /// </summary>
        internal static string Layout_Home {
            get {
                return ResourceManager.GetString("Layout_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выход.
        /// </summary>
        internal static string Layout_LogOff {
            get {
                return ResourceManager.GetString("Layout_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вход.
        /// </summary>
        internal static string Layout_LogOn {
            get {
                return ResourceManager.GetString("Layout_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать учетную запись.
        /// </summary>
        internal static string Layout_Register {
            get {
                return ResourceManager.GetString("Layout_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Репозитории.
        /// </summary>
        internal static string Layout_Repositories {
            get {
                return ResourceManager.GetString("Layout_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonobo Git Server.
        /// </summary>
        internal static string Layout_Title {
            get {
                return ResourceManager.GetString("Layout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На главную.
        /// </summary>
        internal static string Repository_AddressBar_Root {
            get {
                return ResourceManager.GetString("Repository_AddressBar_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администраторы имеют полный доступ к репозиторию. Они также могу изменять метаданные репозитория или удалять его..
        /// </summary>
        internal static string Repository_AdministratorsHint {
            get {
                return ResourceManager.GetString("Repository_AdministratorsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если анонимный доступ разрешен, каждый может считывать, копировать и смотреть метаданные репозитория. Редактирование разрешено только если это настроено в глобальных настройках.
        /// </summary>
        internal static string Repository_AllowAnonymousHint {
            get {
                return ResourceManager.GetString("Repository_AllowAnonymousHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комиты.
        /// </summary>
        internal static string Repository_Commits_Title {
            get {
                return ResourceManager.GetString("Repository_Commits_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавлено.
        /// </summary>
        internal static string Repository_Commit_Added {
            get {
                return ResourceManager.GetString("Repository_Commit_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        internal static string Repository_Commit_Author {
            get {
                return ResourceManager.GetString("Repository_Commit_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта.
        /// </summary>
        internal static string Repository_Commit_AuthorEmail {
            get {
                return ResourceManager.GetString("Repository_Commit_AuthorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Измененные файлы.
        /// </summary>
        internal static string Repository_Commit_Changes {
            get {
                return ResourceManager.GetString("Repository_Commit_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скопировано.
        /// </summary>
        internal static string Repository_Commit_Copied {
            get {
                return ResourceManager.GetString("Repository_Commit_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string Repository_Commit_Date {
            get {
                return ResourceManager.GetString("Repository_Commit_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удален.
        /// </summary>
        internal static string Repository_Commit_Deleted {
            get {
                return ResourceManager.GetString("Repository_Commit_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробности комита.
        /// </summary>
        internal static string Repository_Commit_Detail {
            get {
                return ResourceManager.GetString("Repository_Commit_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комит.
        /// </summary>
        internal static string Repository_Commit_ID {
            get {
                return ResourceManager.GetString("Repository_Commit_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        internal static string Repository_Commit_Message {
            get {
                return ResourceManager.GetString("Repository_Commit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменено.
        /// </summary>
        internal static string Repository_Commit_Modified {
            get {
                return ResourceManager.GetString("Repository_Commit_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Родители.
        /// </summary>
        internal static string Repository_Commit_Parents {
            get {
                return ResourceManager.GetString("Repository_Commit_Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переименовано.
        /// </summary>
        internal static string Repository_Commit_Renamed {
            get {
                return ResourceManager.GetString("Repository_Commit_Renamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дерево.
        /// </summary>
        internal static string Repository_Commit_TreeID {
            get {
                return ResourceManager.GetString("Repository_Commit_TreeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип изменен.
        /// </summary>
        internal static string Repository_Commit_TypeChanged {
            get {
                return ResourceManager.GetString("Repository_Commit_TypeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратно к списку.
        /// </summary>
        internal static string Repository_Create_Back {
            get {
                return ResourceManager.GetString("Repository_Create_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка с таким именем уже существует в вашей папке репозиториев.  Удалите её или выберете другое имя и попробуйте еще раз..
        /// </summary>
        internal static string Repository_Create_DirectoryExists {
            get {
                return ResourceManager.GetString("Repository_Create_DirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Репозиторий создать не удалось. Исправьте ошибки и попробуйте еще раз..
        /// </summary>
        internal static string Repository_Create_Fail {
            get {
                return ResourceManager.GetString("Repository_Create_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Репозиторий с таким именем уже существует.
        /// </summary>
        internal static string Repository_Create_Failure {
            get {
                return ResourceManager.GetString("Repository_Create_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о репозитории.
        /// </summary>
        internal static string Repository_Create_Informations {
            get {
                return ResourceManager.GetString("Repository_Create_Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя не может состоять только из пробелов.
        /// </summary>
        internal static string Repository_Create_NameFailure {
            get {
                return ResourceManager.GetString("Repository_Create_NameFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создано.
        /// </summary>
        internal static string Repository_Create_Submit {
            get {
                return ResourceManager.GetString("Repository_Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Репозиторий был успешно создан.
        /// </summary>
        internal static string Repository_Create_Success {
            get {
                return ResourceManager.GetString("Repository_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новый репозиторий.
        /// </summary>
        internal static string Repository_Create_Title {
            get {
                return ResourceManager.GetString("Repository_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Репозиторий был успешно удален.
        /// </summary>
        internal static string Repository_Delete_Success {
            get {
                return ResourceManager.GetString("Repository_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администраторы.
        /// </summary>
        internal static string Repository_Detail_Administrators {
            get {
                return ResourceManager.GetString("Repository_Detail_Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аноним.
        /// </summary>
        internal static string Repository_Detail_Anonymous {
            get {
                return ResourceManager.GetString("Repository_Detail_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратно к списку.
        /// </summary>
        internal static string Repository_Detail_Back {
            get {
                return ResourceManager.GetString("Repository_Detail_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Repository_Detail_Delete {
            get {
                return ResourceManager.GetString("Repository_Detail_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string Repository_Detail_Description {
            get {
                return ResourceManager.GetString("Repository_Detail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее.
        /// </summary>
        internal static string Repository_Detail_Detail {
            get {
                return ResourceManager.GetString("Repository_Detail_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        internal static string Repository_Detail_Edit {
            get {
                return ResourceManager.GetString("Repository_Detail_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администратор.
        /// </summary>
        internal static string Repository_Detail_IsCurrentUserAdmin {
            get {
                return ResourceManager.GetString("Repository_Detail_IsCurrentUserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение репозитория GIT.
        /// </summary>
        internal static string Repository_Detail_Location {
            get {
                return ResourceManager.GetString("Repository_Detail_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string Repository_Detail_Name {
            get {
                return ResourceManager.GetString("Repository_Detail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string Repository_Detail_No {
            get {
                return ResourceManager.GetString("Repository_Detail_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команды.
        /// </summary>
        internal static string Repository_Detail_Teams {
            get {
                return ResourceManager.GetString("Repository_Detail_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее о репозитории.
        /// </summary>
        internal static string Repository_Detail_Title {
            get {
                return ResourceManager.GetString("Repository_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поставщики.
        /// </summary>
        internal static string Repository_Detail_Users {
            get {
                return ResourceManager.GetString("Repository_Detail_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Repository_Detail_Yes {
            get {
                return ResourceManager.GetString("Repository_Detail_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратно к списку.
        /// </summary>
        internal static string Repository_Edit_Back {
            get {
                return ResourceManager.GetString("Repository_Edit_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы не можете удалить сами себя из Администраторов.
        /// </summary>
        internal static string Repository_Edit_CantRemoveYourself {
            get {
                return ResourceManager.GetString("Repository_Edit_CantRemoveYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Репозиторий обновить не удалось. Исправьте ошибки и попробуйте еще раз..
        /// </summary>
        internal static string Repository_Edit_Fail {
            get {
                return ResourceManager.GetString("Repository_Edit_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Repository_Edit_Submit {
            get {
                return ResourceManager.GetString("Repository_Edit_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать репозиторий.
        /// </summary>
        internal static string Repository_Edit_Title {
            get {
                return ResourceManager.GetString("Repository_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Репозиторий был успешно обновлен.
        /// </summary>
        internal static string Repository_Edit_UpdateSuccess {
            get {
                return ResourceManager.GetString("Repository_Edit_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрируемые репозитории.
        /// </summary>
        internal static string Repository_Index_AdministratedRepositories {
            get {
                return ResourceManager.GetString("Repository_Index_AdministratedRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все репозитории.
        /// </summary>
        internal static string Repository_Index_AllRepositories {
            get {
                return ResourceManager.GetString("Repository_Index_AllRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новый репозиторий.
        /// </summary>
        internal static string Repository_Index_CreateNew {
            get {
                return ResourceManager.GetString("Repository_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет.
        /// </summary>
        internal static string Repository_Index_No {
            get {
                return ResourceManager.GetString("Repository_Index_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Репозитории.
        /// </summary>
        internal static string Repository_Index_Repositories {
            get {
                return ResourceManager.GetString("Repository_Index_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление репозиторием.
        /// </summary>
        internal static string Repository_Index_Title {
            get {
                return ResourceManager.GetString("Repository_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Да.
        /// </summary>
        internal static string Repository_Index_Yes {
            get {
                return ResourceManager.GetString("Repository_Index_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр репозитория.
        /// </summary>
        internal static string Repository_Layout_Browse {
            get {
                return ResourceManager.GetString("Repository_Layout_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комиты.
        /// </summary>
        internal static string Repository_Layout_Commits {
            get {
                return ResourceManager.GetString("Repository_Layout_Commits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать другую ветку.
        /// </summary>
        internal static string Repository_SwitchBranch {
            get {
                return ResourceManager.GetString("Repository_SwitchBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команды имеют полный доступ к репозиторию. Они также могу изменять метаданные репозитория или удалять его..
        /// </summary>
        internal static string Repository_TeamsHint {
            get {
                return ResourceManager.GetString("Repository_TeamsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Автор.
        /// </summary>
        internal static string Repository_Tree_Author {
            get {
                return ResourceManager.GetString("Repository_Tree_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        internal static string Repository_Tree_CommitDate {
            get {
                return ResourceManager.GetString("Repository_Tree_CommitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщение.
        /// </summary>
        internal static string Repository_Tree_CommitMessage {
            get {
                return ResourceManager.GetString("Repository_Tree_CommitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скачать файл.
        /// </summary>
        internal static string Repository_Tree_Download {
            get {
                return ResourceManager.GetString("Repository_Tree_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string Repository_Tree_Name {
            get {
                return ResourceManager.GetString("Repository_Tree_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предпросмотр этого типа файлов невозможно.
        /// </summary>
        internal static string Repository_Tree_PreviewNotSupported {
            get {
                return ResourceManager.GetString("Repository_Tree_PreviewNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр репозитория.
        /// </summary>
        internal static string Repository_Tree_Title {
            get {
                return ResourceManager.GetString("Repository_Tree_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи имеют доступ к этому репозиторию. Они могут копировать, редактировать и смотреть метаданные этого репозитория.
        /// </summary>
        internal static string Repository_UsersHint {
            get {
                return ResourceManager.GetString("Repository_UsersHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сбросить.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешить редактирование анонимных репозиториев. .
        /// </summary>
        internal static string Settings_Global_AllowAnonymousPush {
            get {
                return ResourceManager.GetString("Settings_Global_AllowAnonymousPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешить анонимную регистрацию.
        /// </summary>
        internal static string Settings_Global_AllowAnonymousRegistration {
            get {
                return ResourceManager.GetString("Settings_Global_AllowAnonymousRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если галочка снята, только администраторы могут добавлять новых пользователей и анонимная регистрация отключена.
        /// </summary>
        internal static string Settings_Global_AllowAnonymousRegistration_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_AllowAnonymousRegistration_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разрешить пользователям создавать репозитории.
        /// </summary>
        internal static string Settings_Global_AllowUserRepositoryCreation {
            get {
                return ResourceManager.GetString("Settings_Global_AllowUserRepositoryCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если галочка снята, только администраторы могут создавать репозитории..
        /// </summary>
        internal static string Settings_Global_AllowUserRepositoryCreation_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_AllowUserRepositoryCreation_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Все репозитории хранятся в этой папке.
        /// </summary>
        internal static string Settings_Global_DirectoryHint {
            get {
                return ResourceManager.GetString("Settings_Global_DirectoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Папка репозитория.
        /// </summary>
        internal static string Settings_Global_RepositoryPath {
            get {
                return ResourceManager.GetString("Settings_Global_RepositoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки обновить не удалось. Исправьте ошибки и попробуйте еще раз..
        /// </summary>
        internal static string Settings_Index_Failed {
            get {
                return ResourceManager.GetString("Settings_Index_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Settings_Index_Save {
            get {
                return ResourceManager.GetString("Settings_Index_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Глобальные настройки.
        /// </summary>
        internal static string Settings_Index_Title {
            get {
                return ResourceManager.GetString("Settings_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Глобальные настройки успешно изменены.
        /// </summary>
        internal static string Settings_Index_UpdateSuccess {
            get {
                return ResourceManager.GetString("Settings_Index_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранного пути не существует. Создайте папку, либо выберете другую.
        /// </summary>
        internal static string Settings_RepositoryPathNotExists {
            get {
                return ResourceManager.GetString("Settings_RepositoryPathNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У Вас нет прав для записи в эту папку, выберете другую..
        /// </summary>
        internal static string Settings_RepositoryPathUnauthorized {
            get {
                return ResourceManager.GetString("Settings_RepositoryPathUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратно к списку.
        /// </summary>
        internal static string Team_Create_Back {
            get {
                return ResourceManager.GetString("Team_Create_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новую команду не удалось. Исправьте ошибки и попробуйте еще раз..
        /// </summary>
        internal static string Team_Create_Fail {
            get {
                return ResourceManager.GetString("Team_Create_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда с таким именем уже существует, поэтому создать еще одну не удалось..
        /// </summary>
        internal static string Team_Create_Failure {
            get {
                return ResourceManager.GetString("Team_Create_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        internal static string Team_Create_Submit {
            get {
                return ResourceManager.GetString("Team_Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда была успешно создана..
        /// </summary>
        internal static string Team_Create_Success {
            get {
                return ResourceManager.GetString("Team_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация о команде.
        /// </summary>
        internal static string Team_Create_TeamInformations {
            get {
                return ResourceManager.GetString("Team_Create_TeamInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новую команду.
        /// </summary>
        internal static string Team_Create_Title {
            get {
                return ResourceManager.GetString("Team_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда была удалена..
        /// </summary>
        internal static string Team_Delete_Success {
            get {
                return ResourceManager.GetString("Team_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратно к списку.
        /// </summary>
        internal static string Team_Detail_Back {
            get {
                return ResourceManager.GetString("Team_Detail_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        internal static string Team_Detail_Delete {
            get {
                return ResourceManager.GetString("Team_Detail_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        internal static string Team_Detail_Description {
            get {
                return ResourceManager.GetString("Team_Detail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать.
        /// </summary>
        internal static string Team_Detail_Edit {
            get {
                return ResourceManager.GetString("Team_Detail_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Участники.
        /// </summary>
        internal static string Team_Detail_Members {
            get {
                return ResourceManager.GetString("Team_Detail_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string Team_Detail_Name {
            get {
                return ResourceManager.GetString("Team_Detail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Репозитории.
        /// </summary>
        internal static string Team_Detail_Repositories {
            get {
                return ResourceManager.GetString("Team_Detail_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подробнее о команде.
        /// </summary>
        internal static string Team_Detail_Title {
            get {
                return ResourceManager.GetString("Team_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обратно к списку.
        /// </summary>
        internal static string Team_Edit_Back {
            get {
                return ResourceManager.GetString("Team_Edit_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команду обновить не удалось. Исправьте ошибки и попробуйте еще раз..
        /// </summary>
        internal static string Team_Edit_Failure {
            get {
                return ResourceManager.GetString("Team_Edit_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        internal static string Team_Edit_Submit {
            get {
                return ResourceManager.GetString("Team_Edit_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать команду.
        /// </summary>
        internal static string Team_Edit_Title {
            get {
                return ResourceManager.GetString("Team_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команда была обновлена.
        /// </summary>
        internal static string Team_Edit_UpdateSuccess {
            get {
                return ResourceManager.GetString("Team_Edit_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать новую команду.
        /// </summary>
        internal static string Team_Index_CreateNew {
            get {
                return ResourceManager.GetString("Team_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Команды.
        /// </summary>
        internal static string Team_Index_Teams {
            get {
                return ResourceManager.GetString("Team_Index_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление командами.
        /// </summary>
        internal static string Team_Index_Title {
            get {
                return ResourceManager.GetString("Team_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; и &quot;{1}&quot; должны совпадать..
        /// </summary>
        internal static string Validation_Compare {
            get {
                return ResourceManager.GetString("Validation_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; не является электронной почтой..
        /// </summary>
        internal static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; содержит символы, которые не могут быть использованы в названии файла или папки..
        /// </summary>
        internal static string Validation_FileName {
            get {
                return ResourceManager.GetString("Validation_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; является обязательным..
        /// </summary>
        internal static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; не может быть меньше чем {1} символов..
        /// </summary>
        internal static string Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation_StringLength", resourceCulture);
            }
        }
    }
}
