//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.34014
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonobo.Git.Server.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bonobo.Git.Server.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account with this username already exists. ähnelt.
        /// </summary>
        public static string Account_Create_AccountAlreadyExists {
            get {
                return ResourceManager.GetString("Account_Create_AccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account information ähnelt.
        /// </summary>
        public static string Account_Create_AccountInformation {
            get {
                return ResourceManager.GetString("Account_Create_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm Password ähnelt.
        /// </summary>
        public static string Account_Create_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account_Create_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email ähnelt.
        /// </summary>
        public static string Account_Create_Email {
            get {
                return ResourceManager.GetString("Account_Create_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Account_Create_Name {
            get {
                return ResourceManager.GetString("Account_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string Account_Create_Password {
            get {
                return ResourceManager.GetString("Account_Create_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create ähnelt.
        /// </summary>
        public static string Account_Create_Submit {
            get {
                return ResourceManager.GetString("Account_Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user was created successfully. ähnelt.
        /// </summary>
        public static string Account_Create_Success {
            get {
                return ResourceManager.GetString("Account_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Surname ähnelt.
        /// </summary>
        public static string Account_Create_Surname {
            get {
                return ResourceManager.GetString("Account_Create_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create New Account ähnelt.
        /// </summary>
        public static string Account_Create_Title {
            get {
                return ResourceManager.GetString("Account_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account creation was unsuccessful. Please correct the errors and try again. ähnelt.
        /// </summary>
        public static string Account_Create_Unsuccessfull {
            get {
                return ResourceManager.GetString("Account_Create_Unsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string Account_Create_Username {
            get {
                return ResourceManager.GetString("Account_Create_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can&apos;t delete yourself. ähnelt.
        /// </summary>
        public static string Account_Delete_DeleteCurrentUser {
            get {
                return ResourceManager.GetString("Account_Delete_DeleteCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user was deleted. ähnelt.
        /// </summary>
        public static string Account_Delete_Success {
            get {
                return ResourceManager.GetString("Account_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string Account_Detail_Back {
            get {
                return ResourceManager.GetString("Account_Detail_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string Account_Detail_Delete {
            get {
                return ResourceManager.GetString("Account_Detail_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string Account_Detail_Edit {
            get {
                return ResourceManager.GetString("Account_Detail_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email ähnelt.
        /// </summary>
        public static string Account_Detail_Email {
            get {
                return ResourceManager.GetString("Account_Detail_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Account_Detail_Name {
            get {
                return ResourceManager.GetString("Account_Detail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roles ähnelt.
        /// </summary>
        public static string Account_Detail_Roles {
            get {
                return ResourceManager.GetString("Account_Detail_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Surname ähnelt.
        /// </summary>
        public static string Account_Detail_Surname {
            get {
                return ResourceManager.GetString("Account_Detail_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Detail ähnelt.
        /// </summary>
        public static string Account_Detail_Title {
            get {
                return ResourceManager.GetString("Account_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string Account_Detail_Username {
            get {
                return ResourceManager.GetString("Account_Detail_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string Account_Edit_Back {
            get {
                return ResourceManager.GetString("Account_Edit_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string Account_Edit_Cancel {
            get {
                return ResourceManager.GetString("Account_Edit_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can&apos;t remove yourself from administrators. ähnelt.
        /// </summary>
        public static string Account_Edit_CannotRemoveYourselfFromAdminRole {
            get {
                return ResourceManager.GetString("Account_Edit_CannotRemoveYourselfFromAdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm Password ähnelt.
        /// </summary>
        public static string Account_Edit_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account_Edit_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current Password ähnelt.
        /// </summary>
        public static string Account_Edit_CurrentPassword {
            get {
                return ResourceManager.GetString("Account_Edit_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email ähnelt.
        /// </summary>
        public static string Account_Edit_Email {
            get {
                return ResourceManager.GetString("Account_Edit_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Account_Edit_Name {
            get {
                return ResourceManager.GetString("Account_Edit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New Password ähnelt.
        /// </summary>
        public static string Account_Edit_NewPassword {
            get {
                return ResourceManager.GetString("Account_Edit_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current password should not be empty. ähnelt.
        /// </summary>
        public static string Account_Edit_OldPasswordEmpty {
            get {
                return ResourceManager.GetString("Account_Edit_OldPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password does not match the current password. ähnelt.
        /// </summary>
        public static string Account_Edit_OldPasswordIncorrect {
            get {
                return ResourceManager.GetString("Account_Edit_OldPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roles ähnelt.
        /// </summary>
        public static string Account_Edit_Roles {
            get {
                return ResourceManager.GetString("Account_Edit_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Administrators have access to all repositories and are allowed to do all operations with repositories, teams and users. ähnelt.
        /// </summary>
        public static string Account_Edit_RolesHint {
            get {
                return ResourceManager.GetString("Account_Edit_RolesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Account_Edit_Submit {
            get {
                return ResourceManager.GetString("Account_Edit_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Surname ähnelt.
        /// </summary>
        public static string Account_Edit_Surname {
            get {
                return ResourceManager.GetString("Account_Edit_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit User Account ähnelt.
        /// </summary>
        public static string Account_Edit_Title {
            get {
                return ResourceManager.GetString("Account_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account edit was unsuccessful. Please correct the errors and try again. ähnelt.
        /// </summary>
        public static string Account_Edit_Unsuccessfull {
            get {
                return ResourceManager.GetString("Account_Edit_Unsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The account was updated successfully. ähnelt.
        /// </summary>
        public static string Account_Edit_UpdateSuccess {
            get {
                return ResourceManager.GetString("Account_Edit_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new user ähnelt.
        /// </summary>
        public static string Account_Index_Create {
            get {
                return ResourceManager.GetString("Account_Index_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Users ähnelt.
        /// </summary>
        public static string Account_Index_Title {
            get {
                return ResourceManager.GetString("Account_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Users ähnelt.
        /// </summary>
        public static string Account_Index_Users {
            get {
                return ResourceManager.GetString("Account_Index_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Confirm ähnelt.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string Delete_Back {
            get {
                return ResourceManager.GetString("Delete_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string Delete_Confirm {
            get {
                return ResourceManager.GetString("Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete {0}? ähnelt.
        /// </summary>
        public static string Delete_ConfirmationText {
            get {
                return ResourceManager.GetString("Delete_ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete Confirmation ähnelt.
        /// </summary>
        public static string Delete_Title {
            get {
                return ResourceManager.GetString("Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string Grid_Delete {
            get {
                return ResourceManager.GetString("Grid_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string Grid_Edit {
            get {
                return ResourceManager.GetString("Grid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Official Page ähnelt.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An error occurred when processing your request. Please try again or contact the system administrator. ähnelt.
        /// </summary>
        public static string Home_Error_Text {
            get {
                return ResourceManager.GetString("Home_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An Error Occurred ähnelt.
        /// </summary>
        public static string Home_Error_Title {
            get {
                return ResourceManager.GetString("Home_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account Information ähnelt.
        /// </summary>
        public static string Home_LogOn_AccountInformation {
            get {
                return ResourceManager.GetString("Home_LogOn_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login was unsuccessful. Please correct the errors and try again. ähnelt.
        /// </summary>
        public static string Home_LogOn_Failed {
            get {
                return ResourceManager.GetString("Home_LogOn_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign In ähnelt.
        /// </summary>
        public static string Home_LogOn_LogOn {
            get {
                return ResourceManager.GetString("Home_LogOn_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        public static string Home_LogOn_Password {
            get {
                return ResourceManager.GetString("Home_LogOn_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remember me? ähnelt.
        /// </summary>
        public static string Home_LogOn_RememberMe {
            get {
                return ResourceManager.GetString("Home_LogOn_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign In ähnelt.
        /// </summary>
        public static string Home_LogOn_Title {
            get {
                return ResourceManager.GetString("Home_LogOn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        public static string Home_LogOn_Username {
            get {
                return ResourceManager.GetString("Home_LogOn_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The username or password provided is incorrect. ähnelt.
        /// </summary>
        public static string Home_LogOn_UsernamePasswordIncorrect {
            get {
                return ResourceManager.GetString("Home_LogOn_UsernamePasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The page you were looking for wasn&apos;t found. Please try again or contact the system administrator. ähnelt.
        /// </summary>
        public static string Home_PageNotFound_Text {
            get {
                return ResourceManager.GetString("Home_PageNotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 404 Page Not Found ähnelt.
        /// </summary>
        public static string Home_PageNotFound_Title {
            get {
                return ResourceManager.GetString("Home_PageNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A server error occurred when processing your request. Please try again or contact the system administrator. ähnelt.
        /// </summary>
        public static string Home_ServerError_Text {
            get {
                return ResourceManager.GetString("Home_ServerError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 500 Server Error ähnelt.
        /// </summary>
        public static string Home_ServerError_Title {
            get {
                return ResourceManager.GetString("Home_ServerError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You don&apos;t have permission for the selected action or page. ähnelt.
        /// </summary>
        public static string Home_Unauthorized_Text {
            get {
                return ResourceManager.GetString("Home_Unauthorized_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unauthorized ähnelt.
        /// </summary>
        public static string Home_Unauthorized_Title {
            get {
                return ResourceManager.GetString("Home_Unauthorized_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Item wasn&apos;t found ähnelt.
        /// </summary>
        public static string Item_NotFound {
            get {
                return ResourceManager.GetString("Item_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The item you were looking for wasn&apos;t found. ähnelt.
        /// </summary>
        public static string Item_NotFound_Text {
            get {
                return ResourceManager.GetString("Item_NotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string Layout_About {
            get {
                return ResourceManager.GetString("Layout_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Account Settings ähnelt.
        /// </summary>
        public static string Layout_AccountSettings {
            get {
                return ResourceManager.GetString("Layout_AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Administration ähnelt.
        /// </summary>
        public static string Layout_Administration {
            get {
                return ResourceManager.GetString("Layout_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Layout_AdministrationGlobalSettings {
            get {
                return ResourceManager.GetString("Layout_AdministrationGlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repositories ähnelt.
        /// </summary>
        public static string Layout_AdministrationRepositories {
            get {
                return ResourceManager.GetString("Layout_AdministrationRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teams ähnelt.
        /// </summary>
        public static string Layout_AdministrationTeams {
            get {
                return ResourceManager.GetString("Layout_AdministrationTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Users ähnelt.
        /// </summary>
        public static string Layout_AdministrationUsers {
            get {
                return ResourceManager.GetString("Layout_AdministrationUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All rights reserved. ähnelt.
        /// </summary>
        public static string Layout_Footer_Copyright {
            get {
                return ResourceManager.GetString("Layout_Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string Layout_Home {
            get {
                return ResourceManager.GetString("Layout_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign Out ähnelt.
        /// </summary>
        public static string Layout_LogOff {
            get {
                return ResourceManager.GetString("Layout_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sign In ähnelt.
        /// </summary>
        public static string Layout_LogOn {
            get {
                return ResourceManager.GetString("Layout_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register ähnelt.
        /// </summary>
        public static string Layout_Register {
            get {
                return ResourceManager.GetString("Layout_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repositories ähnelt.
        /// </summary>
        public static string Layout_Repositories {
            get {
                return ResourceManager.GetString("Layout_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bonobo Git Server ähnelt.
        /// </summary>
        public static string Layout_Title {
            get {
                return ResourceManager.GetString("Layout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Home ähnelt.
        /// </summary>
        public static string Repository_AddressBar_Root {
            get {
                return ResourceManager.GetString("Repository_AddressBar_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Administrators have full access to the repository. They can modify repository metadata or delete the repository. ähnelt.
        /// </summary>
        public static string Repository_AdministratorsHint {
            get {
                return ResourceManager.GetString("Repository_AdministratorsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If anonymous access is allowed, everyone can pull or clone the repository and view repository metadata. Push is available only if set in Global Settings. ähnelt.
        /// </summary>
        public static string Repository_AllowAnonymousHint {
            get {
                return ResourceManager.GetString("Repository_AllowAnonymousHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Record user that pushed commits to the server ähnelt.
        /// </summary>
        public static string Repository_AuditPushUserHint {
            get {
                return ResourceManager.GetString("Repository_AuditPushUserHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string Repository_Back {
            get {
                return ResourceManager.GetString("Repository_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository cloning was unsuccessful. Please correct the errors and try again. ähnelt.
        /// </summary>
        public static string Repository_Clone_Fail {
            get {
                return ResourceManager.GetString("Repository_Clone_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clone ähnelt.
        /// </summary>
        public static string Repository_Clone_Submit {
            get {
                return ResourceManager.GetString("Repository_Clone_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository was cloned successfully. ähnelt.
        /// </summary>
        public static string Repository_Clone_Success {
            get {
                return ResourceManager.GetString("Repository_Clone_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clone Repository ähnelt.
        /// </summary>
        public static string Repository_Clone_Title {
            get {
                return ResourceManager.GetString("Repository_Clone_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Added ähnelt.
        /// </summary>
        public static string Repository_Commit_Added {
            get {
                return ResourceManager.GetString("Repository_Commit_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Author ähnelt.
        /// </summary>
        public static string Repository_Commit_Author {
            get {
                return ResourceManager.GetString("Repository_Commit_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Email ähnelt.
        /// </summary>
        public static string Repository_Commit_AuthorEmail {
            get {
                return ResourceManager.GetString("Repository_Commit_AuthorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Changes ähnelt.
        /// </summary>
        public static string Repository_Commit_Changes {
            get {
                return ResourceManager.GetString("Repository_Commit_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copied ähnelt.
        /// </summary>
        public static string Repository_Commit_Copied {
            get {
                return ResourceManager.GetString("Repository_Commit_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string Repository_Commit_Date {
            get {
                return ResourceManager.GetString("Repository_Commit_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Deleted ähnelt.
        /// </summary>
        public static string Repository_Commit_Deleted {
            get {
                return ResourceManager.GetString("Repository_Commit_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commit Detail ähnelt.
        /// </summary>
        public static string Repository_Commit_Detail {
            get {
                return ResourceManager.GetString("Repository_Commit_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        public static string Repository_Commit_Details {
            get {
                return ResourceManager.GetString("Repository_Commit_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commit ähnelt.
        /// </summary>
        public static string Repository_Commit_ID {
            get {
                return ResourceManager.GetString("Repository_Commit_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message ähnelt.
        /// </summary>
        public static string Repository_Commit_Message {
            get {
                return ResourceManager.GetString("Repository_Commit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Modified ähnelt.
        /// </summary>
        public static string Repository_Commit_Modified {
            get {
                return ResourceManager.GetString("Repository_Commit_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not declared ähnelt.
        /// </summary>
        public static string Repository_Commit_NoMessageDeclared {
            get {
                return ResourceManager.GetString("Repository_Commit_NoMessageDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parents ähnelt.
        /// </summary>
        public static string Repository_Commit_Parents {
            get {
                return ResourceManager.GetString("Repository_Commit_Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Renamed ähnelt.
        /// </summary>
        public static string Repository_Commit_Renamed {
            get {
                return ResourceManager.GetString("Repository_Commit_Renamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tree ähnelt.
        /// </summary>
        public static string Repository_Commit_TreeID {
            get {
                return ResourceManager.GetString("Repository_Commit_TreeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Type Changed ähnelt.
        /// </summary>
        public static string Repository_Commit_TypeChanged {
            get {
                return ResourceManager.GetString("Repository_Commit_TypeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commits ähnelt.
        /// </summary>
        public static string Repository_Commits_Title {
            get {
                return ResourceManager.GetString("Repository_Commits_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A directory with this name already exists in your repository folder. Delete this directory or choose another name and try again. ähnelt.
        /// </summary>
        public static string Repository_Create_DirectoryExists {
            get {
                return ResourceManager.GetString("Repository_Create_DirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository creation was unsuccessful. Please correct the errors and try again. ähnelt.
        /// </summary>
        public static string Repository_Create_Fail {
            get {
                return ResourceManager.GetString("Repository_Create_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository with selected name already exists. ähnelt.
        /// </summary>
        public static string Repository_Create_Failure {
            get {
                return ResourceManager.GetString("Repository_Create_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository information ähnelt.
        /// </summary>
        public static string Repository_Create_Informations {
            get {
                return ResourceManager.GetString("Repository_Create_Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Name&quot; shouldn&apos;t contain only whitespace characters. ähnelt.
        /// </summary>
        public static string Repository_Create_NameFailure {
            get {
                return ResourceManager.GetString("Repository_Create_NameFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create ähnelt.
        /// </summary>
        public static string Repository_Create_Submit {
            get {
                return ResourceManager.GetString("Repository_Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository was created successfully. ähnelt.
        /// </summary>
        public static string Repository_Create_Success {
            get {
                return ResourceManager.GetString("Repository_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create New Repository ähnelt.
        /// </summary>
        public static string Repository_Create_Title {
            get {
                return ResourceManager.GetString("Repository_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository was deleted successfully. ähnelt.
        /// </summary>
        public static string Repository_Delete_Success {
            get {
                return ResourceManager.GetString("Repository_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Administrators ähnelt.
        /// </summary>
        public static string Repository_Detail_Administrators {
            get {
                return ResourceManager.GetString("Repository_Detail_Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anonymous ähnelt.
        /// </summary>
        public static string Repository_Detail_Anonymous {
            get {
                return ResourceManager.GetString("Repository_Detail_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Audit Pushes ähnelt.
        /// </summary>
        public static string Repository_Detail_AuditPushUser {
            get {
                return ResourceManager.GetString("Repository_Detail_AuditPushUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string Repository_Detail_Back {
            get {
                return ResourceManager.GetString("Repository_Detail_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string Repository_Detail_Delete {
            get {
                return ResourceManager.GetString("Repository_Detail_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string Repository_Detail_Description {
            get {
                return ResourceManager.GetString("Repository_Detail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Details ähnelt.
        /// </summary>
        public static string Repository_Detail_Detail {
            get {
                return ResourceManager.GetString("Repository_Detail_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string Repository_Detail_Edit {
            get {
                return ResourceManager.GetString("Repository_Detail_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Admin ähnelt.
        /// </summary>
        public static string Repository_Detail_IsCurrentUserAdmin {
            get {
                return ResourceManager.GetString("Repository_Detail_IsCurrentUserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Url ähnelt.
        /// </summary>
        public static string Repository_Detail_Location {
            get {
                return ResourceManager.GetString("Repository_Detail_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Repository_Detail_Name {
            get {
                return ResourceManager.GetString("Repository_Detail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string Repository_Detail_No {
            get {
                return ResourceManager.GetString("Repository_Detail_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Status ähnelt.
        /// </summary>
        public static string Repository_Detail_Status {
            get {
                return ResourceManager.GetString("Repository_Detail_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teams ähnelt.
        /// </summary>
        public static string Repository_Detail_Teams {
            get {
                return ResourceManager.GetString("Repository_Detail_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository Detail ähnelt.
        /// </summary>
        public static string Repository_Detail_Title {
            get {
                return ResourceManager.GetString("Repository_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contributors ähnelt.
        /// </summary>
        public static string Repository_Detail_Users {
            get {
                return ResourceManager.GetString("Repository_Detail_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string Repository_Detail_Yes {
            get {
                return ResourceManager.GetString("Repository_Detail_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string Repository_Edit_Back {
            get {
                return ResourceManager.GetString("Repository_Edit_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can&apos;t remove yourself from administrators. ähnelt.
        /// </summary>
        public static string Repository_Edit_CantRemoveYourself {
            get {
                return ResourceManager.GetString("Repository_Edit_CantRemoveYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository update was unsuccessful. Please correct the errors and try again. ähnelt.
        /// </summary>
        public static string Repository_Edit_Fail {
            get {
                return ResourceManager.GetString("Repository_Edit_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Repository_Edit_Submit {
            get {
                return ResourceManager.GetString("Repository_Edit_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Repository ähnelt.
        /// </summary>
        public static string Repository_Edit_Title {
            get {
                return ResourceManager.GetString("Repository_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository was updated successfully. ähnelt.
        /// </summary>
        public static string Repository_Edit_UpdateSuccess {
            get {
                return ResourceManager.GetString("Repository_Edit_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Administered Repositories ähnelt.
        /// </summary>
        public static string Repository_Index_AdministratedRepositories {
            get {
                return ResourceManager.GetString("Repository_Index_AdministratedRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Repositories ähnelt.
        /// </summary>
        public static string Repository_Index_AllRepositories {
            get {
                return ResourceManager.GetString("Repository_Index_AllRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new repository ähnelt.
        /// </summary>
        public static string Repository_Index_CreateNew {
            get {
                return ResourceManager.GetString("Repository_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        public static string Repository_Index_No {
            get {
                return ResourceManager.GetString("Repository_Index_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repositories ähnelt.
        /// </summary>
        public static string Repository_Index_Repositories {
            get {
                return ResourceManager.GetString("Repository_Index_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repositories ähnelt.
        /// </summary>
        public static string Repository_Index_Title {
            get {
                return ResourceManager.GetString("Repository_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        public static string Repository_Index_Yes {
            get {
                return ResourceManager.GetString("Repository_Index_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository Browser ähnelt.
        /// </summary>
        public static string Repository_Layout_Browse {
            get {
                return ResourceManager.GetString("Repository_Layout_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clone ähnelt.
        /// </summary>
        public static string Repository_Layout_Clone {
            get {
                return ResourceManager.GetString("Repository_Layout_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Commits ähnelt.
        /// </summary>
        public static string Repository_Layout_Commits {
            get {
                return ResourceManager.GetString("Repository_Layout_Commits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Switch current branch ähnelt.
        /// </summary>
        public static string Repository_SwitchBranch {
            get {
                return ResourceManager.GetString("Repository_SwitchBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teams have access to the repository. They can clone, push or pull and view repository metadata. All users in the team can access this repository. ähnelt.
        /// </summary>
        public static string Repository_TeamsHint {
            get {
                return ResourceManager.GetString("Repository_TeamsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Author ähnelt.
        /// </summary>
        public static string Repository_Tree_Author {
            get {
                return ResourceManager.GetString("Repository_Tree_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
        /// </summary>
        public static string Repository_Tree_CommitDate {
            get {
                return ResourceManager.GetString("Repository_Tree_CommitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message ähnelt.
        /// </summary>
        public static string Repository_Tree_CommitMessage {
            get {
                return ResourceManager.GetString("Repository_Tree_CommitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download ähnelt.
        /// </summary>
        public static string Repository_Tree_Download {
            get {
                return ResourceManager.GetString("Repository_Tree_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Repository_Tree_Name {
            get {
                return ResourceManager.GetString("Repository_Tree_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview of this file is not supported. ähnelt.
        /// </summary>
        public static string Repository_Tree_PreviewNotSupported {
            get {
                return ResourceManager.GetString("Repository_Tree_PreviewNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Raw ähnelt.
        /// </summary>
        public static string Repository_Tree_RawDisplay {
            get {
                return ResourceManager.GetString("Repository_Tree_RawDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse Repository ähnelt.
        /// </summary>
        public static string Repository_Tree_Title {
            get {
                return ResourceManager.GetString("Repository_Tree_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Download ähnelt.
        /// </summary>
        public static string Repository_Tree_Zip {
            get {
                return ResourceManager.GetString("Repository_Tree_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Users have access to the repository. They can clone, push or pull and view repository metadata. ähnelt.
        /// </summary>
        public static string Repository_UsersHint {
            get {
                return ResourceManager.GetString("Repository_UsersHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow push for anonymous repositories ähnelt.
        /// </summary>
        public static string Settings_Global_AllowAnonymousPush {
            get {
                return ResourceManager.GetString("Settings_Global_AllowAnonymousPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow anonymous registration ähnelt.
        /// </summary>
        public static string Settings_Global_AllowAnonymousRegistration {
            get {
                return ResourceManager.GetString("Settings_Global_AllowAnonymousRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If checkbox is unchecked, only administrators can add new users and anonymous user registration is disabled. ähnelt.
        /// </summary>
        public static string Settings_Global_AllowAnonymousRegistration_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_AllowAnonymousRegistration_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Allow user repository creation ähnelt.
        /// </summary>
        public static string Settings_Global_AllowUserRepositoryCreation {
            get {
                return ResourceManager.GetString("Settings_Global_AllowUserRepositoryCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die If checkbox is unchecked, only administrators can create repositories. ähnelt.
        /// </summary>
        public static string Settings_Global_AllowUserRepositoryCreation_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_AllowUserRepositoryCreation_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string Settings_Global_DefaultLanguage {
            get {
                return ResourceManager.GetString("Settings_Global_DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language set by default in the application. ähnelt.
        /// </summary>
        public static string Settings_Global_DefaultLanguage_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_DefaultLanguage_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All repositories are stored in this directory. ähnelt.
        /// </summary>
        public static string Settings_Global_DirectoryHint {
            get {
                return ResourceManager.GetString("Settings_Global_DirectoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repository Directory ähnelt.
        /// </summary>
        public static string Settings_Global_RepositoryPath {
            get {
                return ResourceManager.GetString("Settings_Global_RepositoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Site Footer Message ähnelt.
        /// </summary>
        public static string Settings_Global_SiteFooterMessage {
            get {
                return ResourceManager.GetString("Settings_Global_SiteFooterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message displayed in footer area of site pages. ähnelt.
        /// </summary>
        public static string Settings_Global_SiteFooterMessage_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_SiteFooterMessage_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Site Logo URL ähnelt.
        /// </summary>
        public static string Settings_Global_SiteLogoUrl {
            get {
                return ResourceManager.GetString("Settings_Global_SiteLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die URL to a logo to use for the site.  Site-relative (~) paths are supported. ähnelt.
        /// </summary>
        public static string Settings_Global_SiteLogoUrl_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_SiteLogoUrl_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Site Title ähnelt.
        /// </summary>
        public static string Settings_Global_SiteTitle {
            get {
                return ResourceManager.GetString("Settings_Global_SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title for this git site. ähnelt.
        /// </summary>
        public static string Settings_Global_SiteTitle_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_SiteTitle_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings update was unsuccessful. Please correct the errors and try again. ähnelt.
        /// </summary>
        public static string Settings_Index_Failed {
            get {
                return ResourceManager.GetString("Settings_Index_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Settings_Index_Save {
            get {
                return ResourceManager.GetString("Settings_Index_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Settings_Index_Title {
            get {
                return ResourceManager.GetString("Settings_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings updated successfully. ähnelt.
        /// </summary>
        public static string Settings_Index_UpdateSuccess {
            get {
                return ResourceManager.GetString("Settings_Index_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Selected path does not exist. Please create the folder or choose a different one. ähnelt.
        /// </summary>
        public static string Settings_RepositoryPathNotExists {
            get {
                return ResourceManager.GetString("Settings_RepositoryPathNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You don&apos;t have privileges to write to the folder. Please choose a different one. ähnelt.
        /// </summary>
        public static string Settings_RepositoryPathUnauthorized {
            get {
                return ResourceManager.GetString("Settings_RepositoryPathUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Github ähnelt.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string Team_Create_Back {
            get {
                return ResourceManager.GetString("Team_Create_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New team creation was unsuccessful. Please correct the errors and try again. ähnelt.
        /// </summary>
        public static string Team_Create_Fail {
            get {
                return ResourceManager.GetString("Team_Create_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team with selected name already exists. Team wasn&apos;t created. ähnelt.
        /// </summary>
        public static string Team_Create_Failure {
            get {
                return ResourceManager.GetString("Team_Create_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Team_Create_Submit {
            get {
                return ResourceManager.GetString("Team_Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The team was created successfully. ähnelt.
        /// </summary>
        public static string Team_Create_Success {
            get {
                return ResourceManager.GetString("Team_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team information ähnelt.
        /// </summary>
        public static string Team_Create_TeamInformations {
            get {
                return ResourceManager.GetString("Team_Create_TeamInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create New Team ähnelt.
        /// </summary>
        public static string Team_Create_Title {
            get {
                return ResourceManager.GetString("Team_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The team was deleted. ähnelt.
        /// </summary>
        public static string Team_Delete_Success {
            get {
                return ResourceManager.GetString("Team_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string Team_Detail_Back {
            get {
                return ResourceManager.GetString("Team_Detail_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        public static string Team_Detail_Delete {
            get {
                return ResourceManager.GetString("Team_Detail_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        public static string Team_Detail_Description {
            get {
                return ResourceManager.GetString("Team_Detail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit ähnelt.
        /// </summary>
        public static string Team_Detail_Edit {
            get {
                return ResourceManager.GetString("Team_Detail_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Members ähnelt.
        /// </summary>
        public static string Team_Detail_Members {
            get {
                return ResourceManager.GetString("Team_Detail_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        public static string Team_Detail_Name {
            get {
                return ResourceManager.GetString("Team_Detail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repositories ähnelt.
        /// </summary>
        public static string Team_Detail_Repositories {
            get {
                return ResourceManager.GetString("Team_Detail_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team Detail ähnelt.
        /// </summary>
        public static string Team_Detail_Title {
            get {
                return ResourceManager.GetString("Team_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back ähnelt.
        /// </summary>
        public static string Team_Edit_Back {
            get {
                return ResourceManager.GetString("Team_Edit_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team update was unsuccessful. Please correct the errors and try again. ähnelt.
        /// </summary>
        public static string Team_Edit_Failure {
            get {
                return ResourceManager.GetString("Team_Edit_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        public static string Team_Edit_Submit {
            get {
                return ResourceManager.GetString("Team_Edit_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit Team ähnelt.
        /// </summary>
        public static string Team_Edit_Title {
            get {
                return ResourceManager.GetString("Team_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Team was updated successfully. ähnelt.
        /// </summary>
        public static string Team_Edit_UpdateSuccess {
            get {
                return ResourceManager.GetString("Team_Edit_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create new team ähnelt.
        /// </summary>
        public static string Team_Index_CreateNew {
            get {
                return ResourceManager.GetString("Team_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teams ähnelt.
        /// </summary>
        public static string Team_Index_Teams {
            get {
                return ResourceManager.GetString("Team_Index_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Teams ähnelt.
        /// </summary>
        public static string Team_Index_Title {
            get {
                return ResourceManager.GetString("Team_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;{0}&quot; and &quot;{1}&quot; must have the same value. ähnelt.
        /// </summary>
        public static string Validation_Compare {
            get {
                return ResourceManager.GetString("Validation_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;{0}&quot; is not a valid email address. ähnelt.
        /// </summary>
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;{0}&quot; contains characters that can&apos;t be in a file or directory name. ähnelt.
        /// </summary>
        public static string Validation_FileName {
            get {
                return ResourceManager.GetString("Validation_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only characters, numbers, minus and underscore are allowed for &quot;{0}&quot;. ähnelt.
        /// </summary>
        public static string Validation_FileName_Regex {
            get {
                return ResourceManager.GetString("Validation_FileName_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;{0}&quot; is mandatory. ähnelt.
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;{0}&quot; should be shorter than {1} characters. ähnelt.
        /// </summary>
        public static string Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation_StringLength", resourceCulture);
            }
        }
    }
}
