//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bonobo.Git.Server.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bonobo.Git.Server.App_GlobalResources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Account with this username already exists. 的本地化字符串。
        /// </summary>
        public static string Account_Create_AccountAlreadyExists {
            get {
                return ResourceManager.GetString("Account_Create_AccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account information 的本地化字符串。
        /// </summary>
        public static string Account_Create_AccountInformation {
            get {
                return ResourceManager.GetString("Account_Create_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Password 的本地化字符串。
        /// </summary>
        public static string Account_Create_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account_Create_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string Account_Create_Email {
            get {
                return ResourceManager.GetString("Account_Create_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Account_Create_Name {
            get {
                return ResourceManager.GetString("Account_Create_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Account_Create_Password {
            get {
                return ResourceManager.GetString("Account_Create_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string Account_Create_Submit {
            get {
                return ResourceManager.GetString("Account_Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The user was created successfully. 的本地化字符串。
        /// </summary>
        public static string Account_Create_Success {
            get {
                return ResourceManager.GetString("Account_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Surname 的本地化字符串。
        /// </summary>
        public static string Account_Create_Surname {
            get {
                return ResourceManager.GetString("Account_Create_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create New Account 的本地化字符串。
        /// </summary>
        public static string Account_Create_Title {
            get {
                return ResourceManager.GetString("Account_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account creation was unsuccessful. Please correct the errors and try again. 的本地化字符串。
        /// </summary>
        public static string Account_Create_Unsuccessfull {
            get {
                return ResourceManager.GetString("Account_Create_Unsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        public static string Account_Create_Username {
            get {
                return ResourceManager.GetString("Account_Create_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can&apos;t delete yourself. 的本地化字符串。
        /// </summary>
        public static string Account_Delete_DeleteCurrentUser {
            get {
                return ResourceManager.GetString("Account_Delete_DeleteCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The user was deleted. 的本地化字符串。
        /// </summary>
        public static string Account_Delete_Success {
            get {
                return ResourceManager.GetString("Account_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Account_Detail_Back {
            get {
                return ResourceManager.GetString("Account_Detail_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Account_Detail_Delete {
            get {
                return ResourceManager.GetString("Account_Detail_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Account_Detail_Edit {
            get {
                return ResourceManager.GetString("Account_Detail_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string Account_Detail_Email {
            get {
                return ResourceManager.GetString("Account_Detail_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Account_Detail_Name {
            get {
                return ResourceManager.GetString("Account_Detail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Roles 的本地化字符串。
        /// </summary>
        public static string Account_Detail_Roles {
            get {
                return ResourceManager.GetString("Account_Detail_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Surname 的本地化字符串。
        /// </summary>
        public static string Account_Detail_Surname {
            get {
                return ResourceManager.GetString("Account_Detail_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Detail 的本地化字符串。
        /// </summary>
        public static string Account_Detail_Title {
            get {
                return ResourceManager.GetString("Account_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        public static string Account_Detail_Username {
            get {
                return ResourceManager.GetString("Account_Detail_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Account_Edit_Back {
            get {
                return ResourceManager.GetString("Account_Edit_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Account_Edit_Cancel {
            get {
                return ResourceManager.GetString("Account_Edit_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t remove yourself from administrators. 的本地化字符串。
        /// </summary>
        public static string Account_Edit_CannotRemoveYourselfFromAdminRole {
            get {
                return ResourceManager.GetString("Account_Edit_CannotRemoveYourselfFromAdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Password 的本地化字符串。
        /// </summary>
        public static string Account_Edit_ConfirmPassword {
            get {
                return ResourceManager.GetString("Account_Edit_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current Password 的本地化字符串。
        /// </summary>
        public static string Account_Edit_CurrentPassword {
            get {
                return ResourceManager.GetString("Account_Edit_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string Account_Edit_Email {
            get {
                return ResourceManager.GetString("Account_Edit_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Account_Edit_Name {
            get {
                return ResourceManager.GetString("Account_Edit_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New Password 的本地化字符串。
        /// </summary>
        public static string Account_Edit_NewPassword {
            get {
                return ResourceManager.GetString("Account_Edit_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current password should not be empty. 的本地化字符串。
        /// </summary>
        public static string Account_Edit_OldPasswordEmpty {
            get {
                return ResourceManager.GetString("Account_Edit_OldPasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password does not match the current password. 的本地化字符串。
        /// </summary>
        public static string Account_Edit_OldPasswordIncorrect {
            get {
                return ResourceManager.GetString("Account_Edit_OldPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Roles 的本地化字符串。
        /// </summary>
        public static string Account_Edit_Roles {
            get {
                return ResourceManager.GetString("Account_Edit_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Administrators have access to all repositories and are allowed to do all operations with repositories, teams and users. 的本地化字符串。
        /// </summary>
        public static string Account_Edit_RolesHint {
            get {
                return ResourceManager.GetString("Account_Edit_RolesHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Account_Edit_Submit {
            get {
                return ResourceManager.GetString("Account_Edit_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Surname 的本地化字符串。
        /// </summary>
        public static string Account_Edit_Surname {
            get {
                return ResourceManager.GetString("Account_Edit_Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit User Account 的本地化字符串。
        /// </summary>
        public static string Account_Edit_Title {
            get {
                return ResourceManager.GetString("Account_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account edit was unsuccessful. Please correct the errors and try again. 的本地化字符串。
        /// </summary>
        public static string Account_Edit_Unsuccessfull {
            get {
                return ResourceManager.GetString("Account_Edit_Unsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The account was updated successfully. 的本地化字符串。
        /// </summary>
        public static string Account_Edit_UpdateSuccess {
            get {
                return ResourceManager.GetString("Account_Edit_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        public static string Account_Edit_Username {
            get {
                return ResourceManager.GetString("Account_Edit_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create new user 的本地化字符串。
        /// </summary>
        public static string Account_Index_Create {
            get {
                return ResourceManager.GetString("Account_Index_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Users 的本地化字符串。
        /// </summary>
        public static string Account_Index_Title {
            get {
                return ResourceManager.GetString("Account_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Users 的本地化字符串。
        /// </summary>
        public static string Account_Index_Users {
            get {
                return ResourceManager.GetString("Account_Index_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Delete_Back {
            get {
                return ResourceManager.GetString("Delete_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Delete_Confirm {
            get {
                return ResourceManager.GetString("Delete_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Do you really want to delete {0}? 的本地化字符串。
        /// </summary>
        public static string Delete_ConfirmationText {
            get {
                return ResourceManager.GetString("Delete_ConfirmationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete Confirmation 的本地化字符串。
        /// </summary>
        public static string Delete_Title {
            get {
                return ResourceManager.GetString("Delete_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;p&gt;A request has been received to reset your password. 
        ///                           If you did not initiate the request, then please ignore this email.&lt;/p&gt;
        ///                           &lt;p&gt;Please click the following link to reset your password:&lt;/p&gt; 的本地化字符串。
        /// </summary>
        public static string Email_PasswordReset_Body {
            get {
                return ResourceManager.GetString("Email_PasswordReset_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bonobo - Password Reset Request 的本地化字符串。
        /// </summary>
        public static string Email_PasswordReset_Title {
            get {
                return ResourceManager.GetString("Email_PasswordReset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Global 的本地化字符串。
        /// </summary>
        public static string Global {
            get {
                return ResourceManager.GetString("Global", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Grid_Delete {
            get {
                return ResourceManager.GetString("Grid_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Grid_Edit {
            get {
                return ResourceManager.GetString("Grid_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Official Page 的本地化字符串。
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thanks! 的本地化字符串。
        /// </summary>
        public static string Home_About_Thanks {
            get {
                return ResourceManager.GetString("Home_About_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Home_About_Title {
            get {
                return ResourceManager.GetString("Home_About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An error occurred when processing your request. Please try again or contact the system administrator. 的本地化字符串。
        /// </summary>
        public static string Home_Error_Text {
            get {
                return ResourceManager.GetString("Home_Error_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An Error Occurred 的本地化字符串。
        /// </summary>
        public static string Home_Error_Title {
            get {
                return ResourceManager.GetString("Home_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to send email. Validate SMTP settings. 的本地化字符串。
        /// </summary>
        public static string Home_ForgotPassword_EmailError {
            get {
                return ResourceManager.GetString("Home_ForgotPassword_EmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email sent 的本地化字符串。
        /// </summary>
        public static string Home_ForgotPassword_EmailSuccess {
            get {
                return ResourceManager.GetString("Home_ForgotPassword_EmailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forgotten Password Failed. Please correct errors and try again. 的本地化字符串。
        /// </summary>
        public static string Home_ForgotPassword_Failed {
            get {
                return ResourceManager.GetString("Home_ForgotPassword_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forgot Password 的本地化字符串。
        /// </summary>
        public static string Home_ForgotPassword_ForgotPassword {
            get {
                return ResourceManager.GetString("Home_ForgotPassword_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forgotten Password 的本地化字符串。
        /// </summary>
        public static string Home_ForgotPassword_Title {
            get {
                return ResourceManager.GetString("Home_ForgotPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        public static string Home_ForgotPassword_Username {
            get {
                return ResourceManager.GetString("Home_ForgotPassword_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could not find username 的本地化字符串。
        /// </summary>
        public static string Home_ForgotPassword_UserNameFailure {
            get {
                return ResourceManager.GetString("Home_ForgotPassword_UserNameFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Information 的本地化字符串。
        /// </summary>
        public static string Home_LogOn_AccountInformation {
            get {
                return ResourceManager.GetString("Home_LogOn_AccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Login was unsuccessful. Please correct the errors and try again. 的本地化字符串。
        /// </summary>
        public static string Home_LogOn_Failed {
            get {
                return ResourceManager.GetString("Home_LogOn_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Forgot Password? 的本地化字符串。
        /// </summary>
        public static string Home_LogOn_ForgotPassword {
            get {
                return ResourceManager.GetString("Home_LogOn_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign In 的本地化字符串。
        /// </summary>
        public static string Home_LogOn_LogOn {
            get {
                return ResourceManager.GetString("Home_LogOn_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Home_LogOn_Password {
            get {
                return ResourceManager.GetString("Home_LogOn_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remember me? 的本地化字符串。
        /// </summary>
        public static string Home_LogOn_RememberMe {
            get {
                return ResourceManager.GetString("Home_LogOn_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign In 的本地化字符串。
        /// </summary>
        public static string Home_LogOn_Title {
            get {
                return ResourceManager.GetString("Home_LogOn_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        public static string Home_LogOn_Username {
            get {
                return ResourceManager.GetString("Home_LogOn_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The username or password provided is incorrect. 的本地化字符串。
        /// </summary>
        public static string Home_LogOn_UsernamePasswordIncorrect {
            get {
                return ResourceManager.GetString("Home_LogOn_UsernamePasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The page you were looking for wasn&apos;t found. Please try again or contact the system administrator. 的本地化字符串。
        /// </summary>
        public static string Home_PageNotFound_Text {
            get {
                return ResourceManager.GetString("Home_PageNotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 404 Page Not Found 的本地化字符串。
        /// </summary>
        public static string Home_PageNotFound_Title {
            get {
                return ResourceManager.GetString("Home_PageNotFound_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm Password 的本地化字符串。
        /// </summary>
        public static string Home_ResetPassword_ConfirmPassword {
            get {
                return ResourceManager.GetString("Home_ResetPassword_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to reset password 的本地化字符串。
        /// </summary>
        public static string Home_ResetPassword_Failed {
            get {
                return ResourceManager.GetString("Home_ResetPassword_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password 的本地化字符串。
        /// </summary>
        public static string Home_ResetPassword_Password {
            get {
                return ResourceManager.GetString("Home_ResetPassword_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Password 的本地化字符串。
        /// </summary>
        public static string Home_ResetPassword_ResetPassword {
            get {
                return ResourceManager.GetString("Home_ResetPassword_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password reset 的本地化字符串。
        /// </summary>
        public static string Home_ResetPassword_Success {
            get {
                return ResourceManager.GetString("Home_ResetPassword_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset Password 的本地化字符串。
        /// </summary>
        public static string Home_ResetPassword_Title {
            get {
                return ResourceManager.GetString("Home_ResetPassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Username 的本地化字符串。
        /// </summary>
        public static string Home_ResetPassword_Username {
            get {
                return ResourceManager.GetString("Home_ResetPassword_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A server error occurred when processing your request. Please try again or contact the system administrator. 的本地化字符串。
        /// </summary>
        public static string Home_ServerError_Text {
            get {
                return ResourceManager.GetString("Home_ServerError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 500 Server Error 的本地化字符串。
        /// </summary>
        public static string Home_ServerError_Title {
            get {
                return ResourceManager.GetString("Home_ServerError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t have permission for the selected action or page. 的本地化字符串。
        /// </summary>
        public static string Home_Unauthorized_Text {
            get {
                return ResourceManager.GetString("Home_Unauthorized_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unauthorized 的本地化字符串。
        /// </summary>
        public static string Home_Unauthorized_Title {
            get {
                return ResourceManager.GetString("Home_Unauthorized_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item wasn&apos;t found 的本地化字符串。
        /// </summary>
        public static string Item_NotFound {
            get {
                return ResourceManager.GetString("Item_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The item you were looking for wasn&apos;t found. 的本地化字符串。
        /// </summary>
        public static string Item_NotFound_Text {
            get {
                return ResourceManager.GetString("Item_NotFound_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string Layout_About {
            get {
                return ResourceManager.GetString("Layout_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account Settings 的本地化字符串。
        /// </summary>
        public static string Layout_AccountSettings {
            get {
                return ResourceManager.GetString("Layout_AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Administration 的本地化字符串。
        /// </summary>
        public static string Layout_Administration {
            get {
                return ResourceManager.GetString("Layout_Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Layout_AdministrationGlobalSettings {
            get {
                return ResourceManager.GetString("Layout_AdministrationGlobalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repositories 的本地化字符串。
        /// </summary>
        public static string Layout_AdministrationRepositories {
            get {
                return ResourceManager.GetString("Layout_AdministrationRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Teams 的本地化字符串。
        /// </summary>
        public static string Layout_AdministrationTeams {
            get {
                return ResourceManager.GetString("Layout_AdministrationTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Users 的本地化字符串。
        /// </summary>
        public static string Layout_AdministrationUsers {
            get {
                return ResourceManager.GetString("Layout_AdministrationUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All rights reserved. 的本地化字符串。
        /// </summary>
        public static string Layout_Footer_Copyright {
            get {
                return ResourceManager.GetString("Layout_Footer_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Layout_Home {
            get {
                return ResourceManager.GetString("Layout_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign Out 的本地化字符串。
        /// </summary>
        public static string Layout_LogOff {
            get {
                return ResourceManager.GetString("Layout_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign In 的本地化字符串。
        /// </summary>
        public static string Layout_LogOn {
            get {
                return ResourceManager.GetString("Layout_LogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register 的本地化字符串。
        /// </summary>
        public static string Layout_Register {
            get {
                return ResourceManager.GetString("Layout_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repositories 的本地化字符串。
        /// </summary>
        public static string Layout_Repositories {
            get {
                return ResourceManager.GetString("Layout_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bonobo Git Server 的本地化字符串。
        /// </summary>
        public static string Layout_Title {
            get {
                return ResourceManager.GetString("Layout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        public static string Repository_AddressBar_Root {
            get {
                return ResourceManager.GetString("Repository_AddressBar_Root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Administrators have full access to the repository. They can modify repository metadata or delete the repository. 的本地化字符串。
        /// </summary>
        public static string Repository_AdministratorsHint {
            get {
                return ResourceManager.GetString("Repository_AdministratorsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If anonymous access is allowed, everyone can pull or clone the repository and view repository metadata. Push is available only if set in Global Settings. 的本地化字符串。
        /// </summary>
        public static string Repository_AllowAnonymousHint {
            get {
                return ResourceManager.GetString("Repository_AllowAnonymousHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allows anonymous users to push to this repository if anonymous access is granted. If &quot;Global&quot; is selected the option set under your global settings is used. 的本地化字符串。
        /// </summary>
        public static string Repository_AllowAnonymousPushHint {
            get {
                return ResourceManager.GetString("Repository_AllowAnonymousPushHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record user that pushed commits to the server 的本地化字符串。
        /// </summary>
        public static string Repository_AuditPushUserHint {
            get {
                return ResourceManager.GetString("Repository_AuditPushUserHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Repository_Back {
            get {
                return ResourceManager.GetString("Repository_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blame 的本地化字符串。
        /// </summary>
        public static string Repository_Blame_Title {
            get {
                return ResourceManager.GetString("Repository_Blame_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository cloning was unsuccessful. Please correct the errors and try again. 的本地化字符串。
        /// </summary>
        public static string Repository_Clone_Fail {
            get {
                return ResourceManager.GetString("Repository_Clone_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clone 的本地化字符串。
        /// </summary>
        public static string Repository_Clone_Submit {
            get {
                return ResourceManager.GetString("Repository_Clone_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository was cloned successfully. 的本地化字符串。
        /// </summary>
        public static string Repository_Clone_Success {
            get {
                return ResourceManager.GetString("Repository_Clone_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clone Repository 的本地化字符串。
        /// </summary>
        public static string Repository_Clone_Title {
            get {
                return ResourceManager.GetString("Repository_Clone_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Added 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_Added {
            get {
                return ResourceManager.GetString("Repository_Commit_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_Author {
            get {
                return ResourceManager.GetString("Repository_Commit_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Avatar 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_AuthorAvatar {
            get {
                return ResourceManager.GetString("Repository_Commit_AuthorAvatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_AuthorEmail {
            get {
                return ResourceManager.GetString("Repository_Commit_AuthorEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_Changes {
            get {
                return ResourceManager.GetString("Repository_Commit_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copied 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_Copied {
            get {
                return ResourceManager.GetString("Repository_Commit_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_Date {
            get {
                return ResourceManager.GetString("Repository_Commit_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deleted 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_Deleted {
            get {
                return ResourceManager.GetString("Repository_Commit_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commit Detail 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_Detail {
            get {
                return ResourceManager.GetString("Repository_Commit_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_Details {
            get {
                return ResourceManager.GetString("Repository_Commit_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commit 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_ID {
            get {
                return ResourceManager.GetString("Repository_Commit_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_Message {
            get {
                return ResourceManager.GetString("Repository_Commit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modified 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_Modified {
            get {
                return ResourceManager.GetString("Repository_Commit_Modified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not declared 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_NoMessageDeclared {
            get {
                return ResourceManager.GetString("Repository_Commit_NoMessageDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parents 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_Parents {
            get {
                return ResourceManager.GetString("Repository_Commit_Parents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Renamed 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_Renamed {
            get {
                return ResourceManager.GetString("Repository_Commit_Renamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tree 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_TreeID {
            get {
                return ResourceManager.GetString("Repository_Commit_TreeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type Changed 的本地化字符串。
        /// </summary>
        public static string Repository_Commit_TypeChanged {
            get {
                return ResourceManager.GetString("Repository_Commit_TypeChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commits 的本地化字符串。
        /// </summary>
        public static string Repository_Commits_Title {
            get {
                return ResourceManager.GetString("Repository_Commits_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commit 1 的本地化字符串。
        /// </summary>
        public static string Repository_Compare_Commit1 {
            get {
                return ResourceManager.GetString("Repository_Compare_Commit1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commit 2 的本地化字符串。
        /// </summary>
        public static string Repository_Compare_Commit2 {
            get {
                return ResourceManager.GetString("Repository_Compare_Commit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FilePath 的本地化字符串。
        /// </summary>
        public static string Repository_Compare_FilePath {
            get {
                return ResourceManager.GetString("Repository_Compare_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compare 的本地化字符串。
        /// </summary>
        public static string Repository_Compare_Submit {
            get {
                return ResourceManager.GetString("Repository_Compare_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Repository_Create_Back {
            get {
                return ResourceManager.GetString("Repository_Create_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A directory with this name already exists in your repository folder. Delete this directory or choose another name and try again. 的本地化字符串。
        /// </summary>
        public static string Repository_Create_DirectoryExists {
            get {
                return ResourceManager.GetString("Repository_Create_DirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository creation was unsuccessful. Please correct the errors and try again. 的本地化字符串。
        /// </summary>
        public static string Repository_Create_Fail {
            get {
                return ResourceManager.GetString("Repository_Create_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository with selected name already exists. 的本地化字符串。
        /// </summary>
        public static string Repository_Create_Failure {
            get {
                return ResourceManager.GetString("Repository_Create_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository information 的本地化字符串。
        /// </summary>
        public static string Repository_Create_Informations {
            get {
                return ResourceManager.GetString("Repository_Create_Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;Name&quot; shouldn&apos;t contain only whitespace characters. 的本地化字符串。
        /// </summary>
        public static string Repository_Create_NameFailure {
            get {
                return ResourceManager.GetString("Repository_Create_NameFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create 的本地化字符串。
        /// </summary>
        public static string Repository_Create_Submit {
            get {
                return ResourceManager.GetString("Repository_Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository was created successfully. 的本地化字符串。
        /// </summary>
        public static string Repository_Create_Success {
            get {
                return ResourceManager.GetString("Repository_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to &quot;{0}&quot; 的本地化字符串。
        /// </summary>
        public static string Repository_Create_Success_Go_To {
            get {
                return ResourceManager.GetString("Repository_Create_Success_Go_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create New Repository 的本地化字符串。
        /// </summary>
        public static string Repository_Create_Title {
            get {
                return ResourceManager.GetString("Repository_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository was deleted successfully. 的本地化字符串。
        /// </summary>
        public static string Repository_Delete_Success {
            get {
                return ResourceManager.GetString("Repository_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Administrators 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_Administrators {
            get {
                return ResourceManager.GetString("Repository_Detail_Administrators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anonymous push 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_AllowAnonymousPush {
            get {
                return ResourceManager.GetString("Repository_Detail_AllowAnonymousPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Anonymous 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_Anonymous {
            get {
                return ResourceManager.GetString("Repository_Detail_Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Audit Pushes 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_AuditPushUser {
            get {
                return ResourceManager.GetString("Repository_Detail_AuditPushUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_Back {
            get {
                return ResourceManager.GetString("Repository_Detail_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_Delete {
            get {
                return ResourceManager.GetString("Repository_Detail_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_Description {
            get {
                return ResourceManager.GetString("Repository_Detail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Details 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_Detail {
            get {
                return ResourceManager.GetString("Repository_Detail_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_Edit {
            get {
                return ResourceManager.GetString("Repository_Detail_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Group 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_Group {
            get {
                return ResourceManager.GetString("Repository_Detail_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admin 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_IsCurrentUserAdmin {
            get {
                return ResourceManager.GetString("Repository_Detail_IsCurrentUserAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Use global linkify settings 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_LinksUseGlobal {
            get {
                return ResourceManager.GetString("Repository_Detail_LinksUseGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Git URL 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_Location {
            get {
                return ResourceManager.GetString("Repository_Detail_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Personal URL 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_Location_Personal {
            get {
                return ResourceManager.GetString("Repository_Detail_Location_Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Logo (36x36) 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_Logo_PostedFile {
            get {
                return ResourceManager.GetString("Repository_Detail_Logo_PostedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_Name {
            get {
                return ResourceManager.GetString("Repository_Detail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_No {
            get {
                return ResourceManager.GetString("Repository_Detail_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove logo 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_RemoveLogo {
            get {
                return ResourceManager.GetString("Repository_Detail_RemoveLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_Status {
            get {
                return ResourceManager.GetString("Repository_Detail_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Teams 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_Teams {
            get {
                return ResourceManager.GetString("Repository_Detail_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository Detail 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_Title {
            get {
                return ResourceManager.GetString("Repository_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contributors 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_Users {
            get {
                return ResourceManager.GetString("Repository_Detail_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Repository_Detail_Yes {
            get {
                return ResourceManager.GetString("Repository_Detail_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Repository_Edit_Back {
            get {
                return ResourceManager.GetString("Repository_Edit_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can&apos;t remove yourself from administrators. 的本地化字符串。
        /// </summary>
        public static string Repository_Edit_CantRemoveYourself {
            get {
                return ResourceManager.GetString("Repository_Edit_CantRemoveYourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository update was unsuccessful. Please correct the errors and try again. 的本地化字符串。
        /// </summary>
        public static string Repository_Edit_Fail {
            get {
                return ResourceManager.GetString("Repository_Edit_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invalid value provided. 的本地化字符串。
        /// </summary>
        public static string Repository_Edit_InvalidAnonymousPushMode {
            get {
                return ResourceManager.GetString("Repository_Edit_InvalidAnonymousPushMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Repository_Edit_Submit {
            get {
                return ResourceManager.GetString("Repository_Edit_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Repository 的本地化字符串。
        /// </summary>
        public static string Repository_Edit_Title {
            get {
                return ResourceManager.GetString("Repository_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository was updated successfully. 的本地化字符串。
        /// </summary>
        public static string Repository_Edit_UpdateSuccess {
            get {
                return ResourceManager.GetString("Repository_Edit_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy repository URL 的本地化字符串。
        /// </summary>
        public static string Repository_Git_Url_Copy {
            get {
                return ResourceManager.GetString("Repository_Git_Url_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Go to repository 的本地化字符串。
        /// </summary>
        public static string Repository_Go_To_Dropdown {
            get {
                return ResourceManager.GetString("Repository_Go_To_Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History 的本地化字符串。
        /// </summary>
        public static string Repository_History_Title {
            get {
                return ResourceManager.GetString("Repository_History_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Administered Repositories 的本地化字符串。
        /// </summary>
        public static string Repository_Index_AdministratedRepositories {
            get {
                return ResourceManager.GetString("Repository_Index_AdministratedRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All Repositories 的本地化字符串。
        /// </summary>
        public static string Repository_Index_AllRepositories {
            get {
                return ResourceManager.GetString("Repository_Index_AllRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create new repository 的本地化字符串。
        /// </summary>
        public static string Repository_Index_CreateNew {
            get {
                return ResourceManager.GetString("Repository_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string Repository_Index_No {
            get {
                return ResourceManager.GetString("Repository_Index_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repositories 的本地化字符串。
        /// </summary>
        public static string Repository_Index_Repositories {
            get {
                return ResourceManager.GetString("Repository_Index_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sort Group 的本地化字符串。
        /// </summary>
        public static string Repository_Index_SortGroup {
            get {
                return ResourceManager.GetString("Repository_Index_SortGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repositories 的本地化字符串。
        /// </summary>
        public static string Repository_Index_Title {
            get {
                return ResourceManager.GetString("Repository_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Repository_Index_Yes {
            get {
                return ResourceManager.GetString("Repository_Index_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository Browser 的本地化字符串。
        /// </summary>
        public static string Repository_Layout_Browse {
            get {
                return ResourceManager.GetString("Repository_Layout_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clone 的本地化字符串。
        /// </summary>
        public static string Repository_Layout_Clone {
            get {
                return ResourceManager.GetString("Repository_Layout_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Commits 的本地化字符串。
        /// </summary>
        public static string Repository_Layout_Commits {
            get {
                return ResourceManager.GetString("Repository_Layout_Commits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Compare 的本地化字符串。
        /// </summary>
        public static string Repository_Layout_Compare {
            get {
                return ResourceManager.GetString("Repository_Layout_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tags 的本地化字符串。
        /// </summary>
        public static string Repository_Layout_Tags {
            get {
                return ResourceManager.GetString("Repository_Layout_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository requires at least one administrator. 的本地化字符串。
        /// </summary>
        public static string Repository_Needs_Administrator {
            get {
                return ResourceManager.GetString("Repository_Needs_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Group 的本地化字符串。
        /// </summary>
        public static string Repository_No_Group {
            get {
                return ResourceManager.GetString("Repository_No_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy personal repository URL 的本地化字符串。
        /// </summary>
        public static string Repository_Personal_Git_Url_Copy {
            get {
                return ResourceManager.GetString("Repository_Personal_Git_Url_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rescan directory 的本地化字符串。
        /// </summary>
        public static string Repository_Rescan_Directory {
            get {
                return ResourceManager.GetString("Repository_Rescan_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch current branch 的本地化字符串。
        /// </summary>
        public static string Repository_SwitchBranch {
            get {
                return ResourceManager.GetString("Repository_SwitchBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tags 的本地化字符串。
        /// </summary>
        public static string Repository_Tags_Title {
            get {
                return ResourceManager.GetString("Repository_Tags_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Teams have access to the repository. They can clone, push or pull and view repository metadata. All users in the team can access this repository. 的本地化字符串。
        /// </summary>
        public static string Repository_TeamsHint {
            get {
                return ResourceManager.GetString("Repository_TeamsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Author 的本地化字符串。
        /// </summary>
        public static string Repository_Tree_Author {
            get {
                return ResourceManager.GetString("Repository_Tree_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blame 的本地化字符串。
        /// </summary>
        public static string Repository_Tree_Blame {
            get {
                return ResourceManager.GetString("Repository_Tree_Blame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blob 的本地化字符串。
        /// </summary>
        public static string Repository_Tree_Blob {
            get {
                return ResourceManager.GetString("Repository_Tree_Blob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string Repository_Tree_CommitDate {
            get {
                return ResourceManager.GetString("Repository_Tree_CommitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message 的本地化字符串。
        /// </summary>
        public static string Repository_Tree_CommitMessage {
            get {
                return ResourceManager.GetString("Repository_Tree_CommitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Repository_Tree_Download {
            get {
                return ResourceManager.GetString("Repository_Tree_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 History 的本地化字符串。
        /// </summary>
        public static string Repository_Tree_History {
            get {
                return ResourceManager.GetString("Repository_Tree_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Repository_Tree_Name {
            get {
                return ResourceManager.GetString("Repository_Tree_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Preview of this file is not supported. 的本地化字符串。
        /// </summary>
        public static string Repository_Tree_PreviewNotSupported {
            get {
                return ResourceManager.GetString("Repository_Tree_PreviewNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Raw 的本地化字符串。
        /// </summary>
        public static string Repository_Tree_RawDisplay {
            get {
                return ResourceManager.GetString("Repository_Tree_RawDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse Repository 的本地化字符串。
        /// </summary>
        public static string Repository_Tree_Title {
            get {
                return ResourceManager.GetString("Repository_Tree_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Download 的本地化字符串。
        /// </summary>
        public static string Repository_Tree_Zip {
            get {
                return ResourceManager.GetString("Repository_Tree_Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Users have access to the repository. They can clone, push or pull and view repository metadata. 的本地化字符串。
        /// </summary>
        public static string Repository_UsersHint {
            get {
                return ResourceManager.GetString("Repository_UsersHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow push for anonymous repositories 的本地化字符串。
        /// </summary>
        public static string Settings_Global_AllowAnonymousPush {
            get {
                return ResourceManager.GetString("Settings_Global_AllowAnonymousPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow anonymous registration 的本地化字符串。
        /// </summary>
        public static string Settings_Global_AllowAnonymousRegistration {
            get {
                return ResourceManager.GetString("Settings_Global_AllowAnonymousRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If checkbox is unchecked, only administrators can add new users and anonymous user registration is disabled. 的本地化字符串。
        /// </summary>
        public static string Settings_Global_AllowAnonymousRegistration_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_AllowAnonymousRegistration_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow push to create repositories 的本地化字符串。
        /// </summary>
        public static string Settings_Global_AllowPushToCreate {
            get {
                return ResourceManager.GetString("Settings_Global_AllowPushToCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If checkbox is checked, Administrators can push a new repository  的本地化字符串。
        /// </summary>
        public static string Settings_Global_AllowPushToCreate_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_AllowPushToCreate_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Allow user repository creation 的本地化字符串。
        /// </summary>
        public static string Settings_Global_AllowUserRepositoryCreation {
            get {
                return ResourceManager.GetString("Settings_Global_AllowUserRepositoryCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If checkbox is unchecked, only administrators can create repositories. 的本地化字符串。
        /// </summary>
        public static string Settings_Global_AllowUserRepositoryCreation_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_AllowUserRepositoryCreation_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language 的本地化字符串。
        /// </summary>
        public static string Settings_Global_DefaultLanguage {
            get {
                return ResourceManager.GetString("Settings_Global_DefaultLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Language set by default in the application. 的本地化字符串。
        /// </summary>
        public static string Settings_Global_DefaultLanguage_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_DefaultLanguage_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All repositories are stored in this directory. 的本地化字符串。
        /// </summary>
        public static string Settings_Global_DirectoryHint {
            get {
                return ResourceManager.GetString("Settings_Global_DirectoryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Show commit author avatar 的本地化字符串。
        /// </summary>
        public static string Settings_Global_IsCommitAuthorAvatarVisible {
            get {
                return ResourceManager.GetString("Settings_Global_IsCommitAuthorAvatarVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link Regex 的本地化字符串。
        /// </summary>
        public static string Settings_Global_LinksRegex {
            get {
                return ResourceManager.GetString("Settings_Global_LinksRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Link Url 的本地化字符串。
        /// </summary>
        public static string Settings_Global_LinksUrl {
            get {
                return ResourceManager.GetString("Settings_Global_LinksUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This uses the C# regex library to parse the provided regex. Capturing groups are supported.
        ///
        ///The pattern is {0} for the whole regex match.
        ///{1} onwards is each capturing group.
        ///
        ///The regular C# string formatting rules apply: To get {} in your link you need to write {{}}. 的本地化字符串。
        /// </summary>
        public static string Settings_Global_LinksUrl_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_LinksUrl_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repository Directory 的本地化字符串。
        /// </summary>
        public static string Settings_Global_RepositoryPath {
            get {
                return ResourceManager.GetString("Settings_Global_RepositoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site Footer Message 的本地化字符串。
        /// </summary>
        public static string Settings_Global_SiteFooterMessage {
            get {
                return ResourceManager.GetString("Settings_Global_SiteFooterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Message displayed in footer area of site pages. 的本地化字符串。
        /// </summary>
        public static string Settings_Global_SiteFooterMessage_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_SiteFooterMessage_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site Logo URL 的本地化字符串。
        /// </summary>
        public static string Settings_Global_SiteLogoUrl {
            get {
                return ResourceManager.GetString("Settings_Global_SiteLogoUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 URL to a logo to use for the site.  Site-relative (~) paths are supported. 的本地化字符串。
        /// </summary>
        public static string Settings_Global_SiteLogoUrl_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_SiteLogoUrl_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site Title 的本地化字符串。
        /// </summary>
        public static string Settings_Global_SiteTitle {
            get {
                return ResourceManager.GetString("Settings_Global_SiteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Title for this git site. 的本地化字符串。
        /// </summary>
        public static string Settings_Global_SiteTitle_Hint {
            get {
                return ResourceManager.GetString("Settings_Global_SiteTitle_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings update was unsuccessful. Please correct the errors and try again. 的本地化字符串。
        /// </summary>
        public static string Settings_Index_Failed {
            get {
                return ResourceManager.GetString("Settings_Index_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Settings_Index_Save {
            get {
                return ResourceManager.GetString("Settings_Index_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        public static string Settings_Index_Title {
            get {
                return ResourceManager.GetString("Settings_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings updated successfully. 的本地化字符串。
        /// </summary>
        public static string Settings_Index_UpdateSuccess {
            get {
                return ResourceManager.GetString("Settings_Index_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selected path does not exist. Please create the folder or choose a different one. 的本地化字符串。
        /// </summary>
        public static string Settings_RepositoryPathNotExists {
            get {
                return ResourceManager.GetString("Settings_RepositoryPathNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You don&apos;t have privileges to write to the folder. Please choose a different one. 的本地化字符串。
        /// </summary>
        public static string Settings_RepositoryPathUnauthorized {
            get {
                return ResourceManager.GetString("Settings_RepositoryPathUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Github 的本地化字符串。
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Team_Create_Back {
            get {
                return ResourceManager.GetString("Team_Create_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 New team creation was unsuccessful. Please correct the errors and try again. 的本地化字符串。
        /// </summary>
        public static string Team_Create_Fail {
            get {
                return ResourceManager.GetString("Team_Create_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Team with selected name already exists. Team wasn&apos;t created. 的本地化字符串。
        /// </summary>
        public static string Team_Create_Failure {
            get {
                return ResourceManager.GetString("Team_Create_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string Team_Create_Submit {
            get {
                return ResourceManager.GetString("Team_Create_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The team was created successfully. 的本地化字符串。
        /// </summary>
        public static string Team_Create_Success {
            get {
                return ResourceManager.GetString("Team_Create_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Team information 的本地化字符串。
        /// </summary>
        public static string Team_Create_TeamInformations {
            get {
                return ResourceManager.GetString("Team_Create_TeamInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create New Team 的本地化字符串。
        /// </summary>
        public static string Team_Create_Title {
            get {
                return ResourceManager.GetString("Team_Create_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The team was deleted. 的本地化字符串。
        /// </summary>
        public static string Team_Delete_Success {
            get {
                return ResourceManager.GetString("Team_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Team_Detail_Back {
            get {
                return ResourceManager.GetString("Team_Detail_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Team_Detail_Delete {
            get {
                return ResourceManager.GetString("Team_Detail_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Description 的本地化字符串。
        /// </summary>
        public static string Team_Detail_Description {
            get {
                return ResourceManager.GetString("Team_Detail_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        public static string Team_Detail_Edit {
            get {
                return ResourceManager.GetString("Team_Detail_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Members 的本地化字符串。
        /// </summary>
        public static string Team_Detail_Members {
            get {
                return ResourceManager.GetString("Team_Detail_Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name 的本地化字符串。
        /// </summary>
        public static string Team_Detail_Name {
            get {
                return ResourceManager.GetString("Team_Detail_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Repositories 的本地化字符串。
        /// </summary>
        public static string Team_Detail_Repositories {
            get {
                return ResourceManager.GetString("Team_Detail_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Team Detail 的本地化字符串。
        /// </summary>
        public static string Team_Detail_Title {
            get {
                return ResourceManager.GetString("Team_Detail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Back 的本地化字符串。
        /// </summary>
        public static string Team_Edit_Back {
            get {
                return ResourceManager.GetString("Team_Edit_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Team update was unsuccessful. Please correct the errors and try again. 的本地化字符串。
        /// </summary>
        public static string Team_Edit_Failure {
            get {
                return ResourceManager.GetString("Team_Edit_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string Team_Edit_Submit {
            get {
                return ResourceManager.GetString("Team_Edit_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit Team 的本地化字符串。
        /// </summary>
        public static string Team_Edit_Title {
            get {
                return ResourceManager.GetString("Team_Edit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Team was updated successfully. 的本地化字符串。
        /// </summary>
        public static string Team_Edit_UpdateSuccess {
            get {
                return ResourceManager.GetString("Team_Edit_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Create new team 的本地化字符串。
        /// </summary>
        public static string Team_Index_CreateNew {
            get {
                return ResourceManager.GetString("Team_Index_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Teams 的本地化字符串。
        /// </summary>
        public static string Team_Index_Teams {
            get {
                return ResourceManager.GetString("Team_Index_Teams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Teams 的本地化字符串。
        /// </summary>
        public static string Team_Index_Title {
            get {
                return ResourceManager.GetString("Team_Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; and &quot;{1}&quot; must have the same value. 的本地化字符串。
        /// </summary>
        public static string Validation_Compare {
            get {
                return ResourceManager.GetString("Validation_Compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This name has already been taken. 的本地化字符串。
        /// </summary>
        public static string Validation_Duplicate_Name {
            get {
                return ResourceManager.GetString("Validation_Duplicate_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; is not a valid email address. 的本地化字符串。
        /// </summary>
        public static string Validation_Email {
            get {
                return ResourceManager.GetString("Validation_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; contains characters that can&apos;t be in a file or directory name. 的本地化字符串。
        /// </summary>
        public static string Validation_FileName {
            get {
                return ResourceManager.GetString("Validation_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Only characters, numbers, dots, minus and underscore are allowed for &quot;{0}&quot;. 的本地化字符串。
        /// </summary>
        public static string Validation_FileName_Regex {
            get {
                return ResourceManager.GetString("Validation_FileName_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The provided regex has an error. {0} 的本地化字符串。
        /// </summary>
        public static string Validation_Invalid_Regex {
            get {
                return ResourceManager.GetString("Validation_Invalid_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; is mandatory. 的本地化字符串。
        /// </summary>
        public static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;{0}&quot; should be shorter than {1} characters. 的本地化字符串。
        /// </summary>
        public static string Validation_StringLength {
            get {
                return ResourceManager.GetString("Validation_StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
